// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.BrowserDetails")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BrowserDetails {
    #[prost(string, tag = "1")]
    pub user_agent: ::prost::alloc::string::String,
    #[prost(enumeration = "BrowserType", tag = "2")]
    pub browser_type: i32,
    #[prost(string, tag = "3")]
    pub os: ::prost::alloc::string::String,
    #[prost(enumeration = "DeviceType", tag = "6")]
    pub device_type: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.Device")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Device {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub source_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub network: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.ConfigVersion")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConfigVersion {
    #[prost(int32, tag = "3")]
    pub year: i32,
    #[prost(int32, tag = "4")]
    pub month: i32,
    #[prost(int32, tag = "5")]
    pub day: i32,
    #[prost(int32, tag = "7")]
    pub v1: i32,
    #[prost(int32, tag = "9")]
    pub v2: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.SignInGaiaRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignInGaiaRequest {
    #[prost(message, optional, tag = "1")]
    pub auth_message: ::core::option::Option<AuthMessage>,
    #[prost(message, optional, tag = "2")]
    pub inner: ::core::option::Option<sign_in_gaia_request::Inner>,
    #[prost(int32, tag = "3")]
    pub unknown_int3: i32,
    #[prost(string, tag = "4")]
    pub network: ::prost::alloc::string::String,
}
/// Nested message and enum types in `SignInGaiaRequest`.
pub mod sign_in_gaia_request {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(message_name = "authentication.SignInGaiaRequest.Inner")]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Inner {
        #[prost(message, optional, tag = "1")]
        pub device_id: ::core::option::Option<inner::DeviceId>,
        #[prost(message, optional, tag = "36")]
        pub some_data: ::core::option::Option<inner::Data>,
    }
    /// Nested message and enum types in `Inner`.
    pub mod inner {
        #[derive(serde::Serialize, serde::Deserialize)]
        #[derive(::prost_reflect::ReflectMessage)]
        #[prost_reflect(
            message_name = "authentication.SignInGaiaRequest.Inner.DeviceID"
        )]
        #[prost_reflect(
            file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
        )]
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct DeviceId {
            /// 3
            #[prost(int32, tag = "1")]
            pub unknown_int1: i32,
            /// messages-web-{uuid without dashes}
            #[prost(string, tag = "2")]
            pub device_id: ::prost::alloc::string::String,
        }
        #[derive(serde::Serialize, serde::Deserialize)]
        #[derive(::prost_reflect::ReflectMessage)]
        #[prost_reflect(message_name = "authentication.SignInGaiaRequest.Inner.Data")]
        #[prost_reflect(
            file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
        )]
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct Data {
            /// maybe an encryption key?
            #[prost(bytes = "vec", tag = "3")]
            pub some_data: ::prost::alloc::vec::Vec<u8>,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.SignInGaiaResponse")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignInGaiaResponse {
    #[prost(message, optional, tag = "1")]
    pub header: ::core::option::Option<sign_in_gaia_response::Header>,
    #[prost(string, tag = "2")]
    pub maybe_browser_uuid: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub device_data: ::core::option::Option<sign_in_gaia_response::DeviceData>,
    #[prost(message, optional, tag = "4")]
    pub token_data: ::core::option::Option<TokenData>,
}
/// Nested message and enum types in `SignInGaiaResponse`.
pub mod sign_in_gaia_response {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(message_name = "authentication.SignInGaiaResponse.Header")]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Header {
        #[prost(uint64, tag = "2")]
        pub unknown_int2: u64,
        #[prost(int64, tag = "4")]
        pub unknown_timestamp: i64,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(message_name = "authentication.SignInGaiaResponse.DeviceData")]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct DeviceData {
        #[prost(message, optional, tag = "1")]
        pub device_wrapper: ::core::option::Option<device_data::DeviceWrapper>,
        #[prost(message, repeated, tag = "2")]
        pub unknown_items2: ::prost::alloc::vec::Vec<
            super::rpc_gaia_data::unknown_container::item2::Item1,
        >,
        /// index 4 is some unknown field with no real data
        #[prost(message, repeated, tag = "3")]
        pub unknown_items3: ::prost::alloc::vec::Vec<
            super::rpc_gaia_data::unknown_container::Item4,
        >,
    }
    /// Nested message and enum types in `DeviceData`.
    pub mod device_data {
        #[derive(serde::Serialize, serde::Deserialize)]
        #[derive(::prost_reflect::ReflectMessage)]
        #[prost_reflect(
            message_name = "authentication.SignInGaiaResponse.DeviceData.DeviceWrapper"
        )]
        #[prost_reflect(
            file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
        )]
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct DeviceWrapper {
            #[prost(message, optional, tag = "1")]
            pub device: ::core::option::Option<super::super::Device>,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.GaiaPairingRequestContainer")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GaiaPairingRequestContainer {
    #[prost(string, tag = "1")]
    pub pairing_attempt_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub browser_details: ::core::option::Option<BrowserDetails>,
    #[prost(int64, tag = "3")]
    pub start_timestamp: i64,
    #[prost(bytes = "vec", tag = "4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag = "5")]
    pub proposed_verification_code_version: i32,
    #[prost(int32, tag = "6")]
    pub proposed_key_derivation_version: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.GaiaPairingResponseContainer")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GaiaPairingResponseContainer {
    #[prost(int32, tag = "1")]
    pub finish_error_type: i32,
    #[prost(enumeration = "GaiaPairingErrorCode", tag = "2")]
    pub finish_error_code: i32,
    /// For init, 1
    #[prost(int32, tag = "3")]
    pub unknown_int3: i32,
    #[prost(string, tag = "4")]
    pub session_uuid: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "5")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag = "6")]
    pub confirmed_verification_code_version: i32,
    #[prost(int32, tag = "7")]
    pub confirmed_key_derivation_version: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.RevokeGaiaPairingRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokeGaiaPairingRequest {
    #[prost(string, tag = "1")]
    pub pairing_attempt_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.RPCGaiaData")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RpcGaiaData {
    /// 9
    #[prost(int32, tag = "1")]
    pub command: i32,
    #[prost(message, optional, tag = "108")]
    pub maybe_server_data: ::core::option::Option<rpc_gaia_data::UnknownContainer>,
}
/// Nested message and enum types in `RPCGaiaData`.
pub mod rpc_gaia_data {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(message_name = "authentication.RPCGaiaData.UnknownContainer")]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct UnknownContainer {
        #[prost(message, optional, tag = "2")]
        pub item2: ::core::option::Option<unknown_container::Item2>,
        /// pairing timestamp?
        #[prost(int64, tag = "3")]
        pub unknown_timestamp_microseconds: i64,
        #[prost(message, repeated, tag = "4")]
        pub item4: ::prost::alloc::vec::Vec<unknown_container::Item4>,
    }
    /// Nested message and enum types in `UnknownContainer`.
    pub mod unknown_container {
        #[derive(serde::Serialize, serde::Deserialize)]
        #[derive(::prost_reflect::ReflectMessage)]
        #[prost_reflect(
            message_name = "authentication.RPCGaiaData.UnknownContainer.Item2"
        )]
        #[prost_reflect(
            file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
        )]
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct Item2 {
            #[prost(message, repeated, tag = "1")]
            pub item1: ::prost::alloc::vec::Vec<item2::Item1>,
        }
        /// Nested message and enum types in `Item2`.
        pub mod item2 {
            #[derive(serde::Serialize, serde::Deserialize)]
            #[derive(::prost_reflect::ReflectMessage)]
            #[prost_reflect(
                message_name = "authentication.RPCGaiaData.UnknownContainer.Item2.Item1"
            )]
            #[prost_reflect(
                file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
            )]
            #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
            pub struct Item1 {
                #[prost(string, tag = "1")]
                pub dest_or_source_uuid: ::prost::alloc::string::String,
                /// 1 for destination device, 6 for local device?
                #[prost(int32, tag = "4")]
                pub unknown_int4: i32,
                #[prost(string, tag = "5")]
                pub language_code: ::prost::alloc::string::String,
                #[prost(uint64, tag = "7")]
                pub unknown_big_int7: u64,
            }
        }
        #[derive(serde::Serialize, serde::Deserialize)]
        #[derive(::prost_reflect::ReflectMessage)]
        #[prost_reflect(
            message_name = "authentication.RPCGaiaData.UnknownContainer.Item4"
        )]
        #[prost_reflect(
            file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
        )]
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct Item4 {
            #[prost(string, tag = "1")]
            pub dest_or_source_uuid: ::prost::alloc::string::String,
            /// 1 for destination device, 6 for local device?
            #[prost(int32, tag = "3")]
            pub unknown_int3: i32,
            /// always 6?
            #[prost(int32, tag = "4")]
            pub unknown_int4: i32,
            /// maybe device creation ts?
            #[prost(int64, tag = "7")]
            pub unknown_timestamp_microseconds: i64,
            #[prost(message, optional, tag = "8")]
            pub item8: ::core::option::Option<item4::Item8>,
        }
        /// Nested message and enum types in `Item4`.
        pub mod item4 {
            #[derive(serde::Serialize, serde::Deserialize)]
            #[derive(::prost_reflect::ReflectMessage)]
            #[prost_reflect(
                message_name = "authentication.RPCGaiaData.UnknownContainer.Item4.Item8"
            )]
            #[prost_reflect(
                file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
            )]
            #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
            pub struct Item8 {
                /// present for destination device?
                #[prost(int32, tag = "1")]
                pub unknown_int1: i32,
                /// present for destination device?
                #[prost(int32, tag = "2")]
                pub unknown_timestamp: i32,
                /// present for local device?
                #[prost(bytes = "vec", tag = "3")]
                pub unknown_bytes: ::prost::alloc::vec::Vec<u8>,
            }
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.AuthenticationContainer")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthenticationContainer {
    #[prost(message, optional, tag = "1")]
    pub auth_message: ::core::option::Option<AuthMessage>,
    #[prost(message, optional, tag = "3")]
    pub browser_details: ::core::option::Option<BrowserDetails>,
    #[prost(oneof = "authentication_container::Data", tags = "4, 5")]
    pub data: ::core::option::Option<authentication_container::Data>,
}
/// Nested message and enum types in `AuthenticationContainer`.
pub mod authentication_container {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "4")]
        KeyData(super::KeyData),
        #[prost(message, tag = "5")]
        DeviceData(super::CurrentDeviceData),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.AuthMessage")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthMessage {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub network: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "6")]
    pub tachyon_auth_token: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "7")]
    pub config_version: ::core::option::Option<ConfigVersion>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.RevokeRelayPairingRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokeRelayPairingRequest {
    #[prost(message, optional, tag = "1")]
    pub auth_message: ::core::option::Option<AuthMessage>,
    #[prost(message, optional, tag = "2")]
    pub browser: ::core::option::Option<Device>,
}
/// field 1 is an object with an unknown int64 in field 2
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.RevokeRelayPairingResponse")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokeRelayPairingResponse {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.RegisterRefreshRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterRefreshRequest {
    #[prost(message, optional, tag = "1")]
    pub message_auth: ::core::option::Option<AuthMessage>,
    #[prost(message, optional, tag = "2")]
    pub curr_browser_device: ::core::option::Option<Device>,
    #[prost(int64, tag = "3")]
    pub unix_timestamp: i64,
    #[prost(bytes = "vec", tag = "4")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "13")]
    pub parameters: ::core::option::Option<register_refresh_request::Parameters>,
    #[prost(int32, tag = "16")]
    pub message_type: i32,
}
/// Nested message and enum types in `RegisterRefreshRequest`.
pub mod register_refresh_request {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(
        message_name = "authentication.RegisterRefreshRequest.PushRegistration"
    )]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct PushRegistration {
        #[prost(string, tag = "1")]
        pub r#type: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub url: ::prost::alloc::string::String,
        #[prost(string, tag = "3")]
        pub p256dh: ::prost::alloc::string::String,
        #[prost(string, tag = "4")]
        pub auth: ::prost::alloc::string::String,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(
        message_name = "authentication.RegisterRefreshRequest.MoreParameters"
    )]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct MoreParameters {
        #[prost(int32, tag = "1")]
        pub three: i32,
        #[prost(message, optional, tag = "102")]
        pub push_reg: ::core::option::Option<PushRegistration>,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(message_name = "authentication.RegisterRefreshRequest.Parameters")]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Parameters {
        #[prost(message, optional, tag = "9")]
        pub empty_arr: ::core::option::Option<super::super::util::EmptyArr>,
        #[prost(message, optional, tag = "23")]
        pub more_parameters: ::core::option::Option<MoreParameters>,
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.RegisterRefreshResponse")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterRefreshResponse {
    #[prost(message, optional, tag = "2")]
    pub token_data: ::core::option::Option<TokenData>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.RegisterPhoneRelayResponse")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterPhoneRelayResponse {
    #[prost(message, optional, tag = "1")]
    pub coordinates: ::core::option::Option<CoordinateMessage>,
    #[prost(message, optional, tag = "2")]
    pub browser: ::core::option::Option<Device>,
    #[prost(bytes = "vec", tag = "3")]
    pub pairing_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "4")]
    pub valid_for: i64,
    #[prost(message, optional, tag = "5")]
    pub auth_key_data: ::core::option::Option<TokenData>,
    #[prost(string, tag = "6")]
    pub response_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.CoordinateMessage")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CoordinateMessage {
    #[prost(int64, tag = "2")]
    pub coord1: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.RefreshPhoneRelayResponse")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RefreshPhoneRelayResponse {
    #[prost(message, optional, tag = "1")]
    pub coordinates: ::core::option::Option<CoordinateMessage>,
    #[prost(bytes = "vec", tag = "2")]
    pub pair_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "3")]
    pub valid_for: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.WebEncryptionKeyResponse")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WebEncryptionKeyResponse {
    #[prost(message, optional, tag = "1")]
    pub coordinates: ::core::option::Option<CoordinateMessage>,
    #[prost(bytes = "vec", tag = "2")]
    pub key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.ErrorResponse")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ErrorResponse {
    /// 5?
    #[prost(int64, tag = "1")]
    pub r#type: i64,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub class: ::prost::alloc::vec::Vec<error_response::ErrorClass>,
}
/// Nested message and enum types in `ErrorResponse`.
pub mod error_response {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(message_name = "authentication.ErrorResponse.ErrorClass")]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct ErrorClass {
        /// 2: {1: 1}
        #[prost(string, tag = "1")]
        pub class: ::prost::alloc::string::String,
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.ECDSAKeys")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EcdsaKeys {
    /// idk?
    #[prost(int64, tag = "1")]
    pub field1: i64,
    #[prost(bytes = "vec", tag = "2")]
    pub encrypted_keys: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.CurrentDeviceData")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CurrentDeviceData {
    #[prost(message, optional, tag = "1")]
    pub browser: ::core::option::Option<Device>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.KeyData")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct KeyData {
    #[prost(message, optional, tag = "1")]
    pub mobile: ::core::option::Option<Device>,
    #[prost(message, optional, tag = "6")]
    pub ecdsa_keys: ::core::option::Option<EcdsaKeys>,
    #[prost(message, optional, tag = "2")]
    pub web_auth_key_data: ::core::option::Option<WebAuthKey>,
    #[prost(message, optional, tag = "3")]
    pub browser: ::core::option::Option<Device>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.WebAuthKey")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WebAuthKey {
    #[prost(bytes = "vec", tag = "1")]
    pub web_auth_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "2")]
    pub valid_for: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.URLData")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UrlData {
    #[prost(bytes = "vec", tag = "1")]
    pub pairing_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub aes_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub hmac_key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.TokenData")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TokenData {
    #[prost(bytes = "vec", tag = "1")]
    pub tachyon_auth_token: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "2")]
    pub ttl: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.PairedData")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PairedData {
    #[prost(message, optional, tag = "1")]
    pub mobile: ::core::option::Option<Device>,
    #[prost(message, optional, tag = "2")]
    pub token_data: ::core::option::Option<TokenData>,
    #[prost(message, optional, tag = "3")]
    pub browser: ::core::option::Option<Device>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "authentication.RevokePairData")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokePairData {
    #[prost(message, optional, tag = "1")]
    pub revoked_device: ::core::option::Option<Device>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BrowserType {
    UnknownBrowserType = 0,
    Other = 1,
    Chrome = 2,
    Firefox = 3,
    Safari = 4,
    Opera = 5,
    Ie = 6,
    Edge = 7,
}
impl BrowserType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UnknownBrowserType => "UNKNOWN_BROWSER_TYPE",
            Self::Other => "OTHER",
            Self::Chrome => "CHROME",
            Self::Firefox => "FIREFOX",
            Self::Safari => "SAFARI",
            Self::Opera => "OPERA",
            Self::Ie => "IE",
            Self::Edge => "EDGE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_BROWSER_TYPE" => Some(Self::UnknownBrowserType),
            "OTHER" => Some(Self::Other),
            "CHROME" => Some(Self::Chrome),
            "FIREFOX" => Some(Self::Firefox),
            "SAFARI" => Some(Self::Safari),
            "OPERA" => Some(Self::Opera),
            "IE" => Some(Self::Ie),
            "EDGE" => Some(Self::Edge),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DeviceType {
    UnknownDeviceType = 0,
    Web = 1,
    Tablet = 2,
    Pwa = 3,
}
impl DeviceType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UnknownDeviceType => "UNKNOWN_DEVICE_TYPE",
            Self::Web => "WEB",
            Self::Tablet => "TABLET",
            Self::Pwa => "PWA",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_DEVICE_TYPE" => Some(Self::UnknownDeviceType),
            "WEB" => Some(Self::Web),
            "TABLET" => Some(Self::Tablet),
            "PWA" => Some(Self::Pwa),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum GaiaPairingErrorCode {
    None = 0,
    Ukey2AlertError = 1,
    RequestOutOfDate = 2,
    RequestNotReceivedQuickly = 3,
    InvalidUser = 4,
    WrongVerificationCodeSelected = 5,
    VerificationTimedOut = 6,
    UserCanceledVerification = 7,
    Ukey2OtherError = 8,
    VerificationEmojiDownloadFailed = 9,
    NotLatestAttempt = 10,
    VerificationDataServiceNotPresent = 11,
    VerificationIntentsNotPresent = 12,
    WrongUkey2MessageType = 13,
    RequestCompleteWithUnknownResult = 14,
    PhoneNotAwaitingConfirmation = 15,
    Ukey2MessageMissing = 16,
    ClientInitTimeout = 17,
    ClientFinishedTimeout = 18,
    Unknown = 19,
    WebCancelButtonClicked = 20,
    WebBackButtonClicked = 21,
    WebLeavePairPage = 22,
    NewRequestWhileWaitingForVerification = 23,
    Ukey2HandshakeError = 24,
    VerificationCodeRevisionMismatch = 25,
    UserCanceledVerificationOnWeb = 26,
    UserDeniedVerificationNotMe = 27,
    KeyDerivationRevisionMismatch = 28,
    CmsBackupKeyNotFound = 29,
    UnableToEncryptCmsBackupKey = 30,
    UnableToDecryptCmsBackupKey = 31,
}
impl GaiaPairingErrorCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::None => "NONE",
            Self::Ukey2AlertError => "UKEY2_ALERT_ERROR",
            Self::RequestOutOfDate => "REQUEST_OUT_OF_DATE",
            Self::RequestNotReceivedQuickly => "REQUEST_NOT_RECEIVED_QUICKLY",
            Self::InvalidUser => "INVALID_USER",
            Self::WrongVerificationCodeSelected => "WRONG_VERIFICATION_CODE_SELECTED",
            Self::VerificationTimedOut => "VERIFICATION_TIMED_OUT",
            Self::UserCanceledVerification => "USER_CANCELED_VERIFICATION",
            Self::Ukey2OtherError => "UKEY2_OTHER_ERROR",
            Self::VerificationEmojiDownloadFailed => "VERIFICATION_EMOJI_DOWNLOAD_FAILED",
            Self::NotLatestAttempt => "NOT_LATEST_ATTEMPT",
            Self::VerificationDataServiceNotPresent => {
                "VERIFICATION_DATA_SERVICE_NOT_PRESENT"
            }
            Self::VerificationIntentsNotPresent => "VERIFICATION_INTENTS_NOT_PRESENT",
            Self::WrongUkey2MessageType => "WRONG_UKEY2_MESSAGE_TYPE",
            Self::RequestCompleteWithUnknownResult => {
                "REQUEST_COMPLETE_WITH_UNKNOWN_RESULT"
            }
            Self::PhoneNotAwaitingConfirmation => "PHONE_NOT_AWAITING_CONFIRMATION",
            Self::Ukey2MessageMissing => "UKEY2_MESSAGE_MISSING",
            Self::ClientInitTimeout => "CLIENT_INIT_TIMEOUT",
            Self::ClientFinishedTimeout => "CLIENT_FINISHED_TIMEOUT",
            Self::Unknown => "UNKNOWN",
            Self::WebCancelButtonClicked => "WEB_CANCEL_BUTTON_CLICKED",
            Self::WebBackButtonClicked => "WEB_BACK_BUTTON_CLICKED",
            Self::WebLeavePairPage => "WEB_LEAVE_PAIR_PAGE",
            Self::NewRequestWhileWaitingForVerification => {
                "NEW_REQUEST_WHILE_WAITING_FOR_VERIFICATION"
            }
            Self::Ukey2HandshakeError => "UKEY2_HANDSHAKE_ERROR",
            Self::VerificationCodeRevisionMismatch => {
                "VERIFICATION_CODE_REVISION_MISMATCH"
            }
            Self::UserCanceledVerificationOnWeb => "USER_CANCELED_VERIFICATION_ON_WEB",
            Self::UserDeniedVerificationNotMe => "USER_DENIED_VERIFICATION_NOT_ME",
            Self::KeyDerivationRevisionMismatch => "KEY_DERIVATION_REVISION_MISMATCH",
            Self::CmsBackupKeyNotFound => "CMS_BACKUP_KEY_NOT_FOUND",
            Self::UnableToEncryptCmsBackupKey => "UNABLE_TO_ENCRYPT_CMS_BACKUP_KEY",
            Self::UnableToDecryptCmsBackupKey => "UNABLE_TO_DECRYPT_CMS_BACKUP_KEY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NONE" => Some(Self::None),
            "UKEY2_ALERT_ERROR" => Some(Self::Ukey2AlertError),
            "REQUEST_OUT_OF_DATE" => Some(Self::RequestOutOfDate),
            "REQUEST_NOT_RECEIVED_QUICKLY" => Some(Self::RequestNotReceivedQuickly),
            "INVALID_USER" => Some(Self::InvalidUser),
            "WRONG_VERIFICATION_CODE_SELECTED" => {
                Some(Self::WrongVerificationCodeSelected)
            }
            "VERIFICATION_TIMED_OUT" => Some(Self::VerificationTimedOut),
            "USER_CANCELED_VERIFICATION" => Some(Self::UserCanceledVerification),
            "UKEY2_OTHER_ERROR" => Some(Self::Ukey2OtherError),
            "VERIFICATION_EMOJI_DOWNLOAD_FAILED" => {
                Some(Self::VerificationEmojiDownloadFailed)
            }
            "NOT_LATEST_ATTEMPT" => Some(Self::NotLatestAttempt),
            "VERIFICATION_DATA_SERVICE_NOT_PRESENT" => {
                Some(Self::VerificationDataServiceNotPresent)
            }
            "VERIFICATION_INTENTS_NOT_PRESENT" => {
                Some(Self::VerificationIntentsNotPresent)
            }
            "WRONG_UKEY2_MESSAGE_TYPE" => Some(Self::WrongUkey2MessageType),
            "REQUEST_COMPLETE_WITH_UNKNOWN_RESULT" => {
                Some(Self::RequestCompleteWithUnknownResult)
            }
            "PHONE_NOT_AWAITING_CONFIRMATION" => Some(Self::PhoneNotAwaitingConfirmation),
            "UKEY2_MESSAGE_MISSING" => Some(Self::Ukey2MessageMissing),
            "CLIENT_INIT_TIMEOUT" => Some(Self::ClientInitTimeout),
            "CLIENT_FINISHED_TIMEOUT" => Some(Self::ClientFinishedTimeout),
            "UNKNOWN" => Some(Self::Unknown),
            "WEB_CANCEL_BUTTON_CLICKED" => Some(Self::WebCancelButtonClicked),
            "WEB_BACK_BUTTON_CLICKED" => Some(Self::WebBackButtonClicked),
            "WEB_LEAVE_PAIR_PAGE" => Some(Self::WebLeavePairPage),
            "NEW_REQUEST_WHILE_WAITING_FOR_VERIFICATION" => {
                Some(Self::NewRequestWhileWaitingForVerification)
            }
            "UKEY2_HANDSHAKE_ERROR" => Some(Self::Ukey2HandshakeError),
            "VERIFICATION_CODE_REVISION_MISMATCH" => {
                Some(Self::VerificationCodeRevisionMismatch)
            }
            "USER_CANCELED_VERIFICATION_ON_WEB" => {
                Some(Self::UserCanceledVerificationOnWeb)
            }
            "USER_DENIED_VERIFICATION_NOT_ME" => Some(Self::UserDeniedVerificationNotMe),
            "KEY_DERIVATION_REVISION_MISMATCH" => {
                Some(Self::KeyDerivationRevisionMismatch)
            }
            "CMS_BACKUP_KEY_NOT_FOUND" => Some(Self::CmsBackupKeyNotFound),
            "UNABLE_TO_ENCRYPT_CMS_BACKUP_KEY" => Some(Self::UnableToEncryptCmsBackupKey),
            "UNABLE_TO_DECRYPT_CMS_BACKUP_KEY" => Some(Self::UnableToDecryptCmsBackupKey),
            _ => None,
        }
    }
}
