// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.NotifyDittoActivityRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NotifyDittoActivityRequest {
    /// This is not actually a boolean: after logging out, field 2 has value 2, and field 3 has value 1.
    #[prost(bool, tag = "2")]
    pub success: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.NotifyDittoActivityResponse")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NotifyDittoActivityResponse {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.ReceiveMessagesRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReceiveMessagesRequest {
    #[prost(message, optional, tag = "1")]
    pub auth: ::core::option::Option<super::authentication::AuthMessage>,
    #[prost(message, optional, tag = "4")]
    pub unknown: ::core::option::Option<receive_messages_request::UnknownEmptyObject2>,
}
/// Nested message and enum types in `ReceiveMessagesRequest`.
pub mod receive_messages_request {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(message_name = "client.ReceiveMessagesRequest.UnknownEmptyObject1")]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct UnknownEmptyObject1 {}
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(message_name = "client.ReceiveMessagesRequest.UnknownEmptyObject2")]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct UnknownEmptyObject2 {
        #[prost(message, optional, tag = "2")]
        pub unknown: ::core::option::Option<UnknownEmptyObject1>,
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.MessageReadRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageReadRequest {
    #[prost(string, tag = "2")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub message_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.AckMessageRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AckMessageRequest {
    #[prost(message, optional, tag = "1")]
    pub auth_data: ::core::option::Option<super::authentication::AuthMessage>,
    #[prost(message, optional, tag = "2")]
    pub empty_arr: ::core::option::Option<super::util::EmptyArr>,
    #[prost(message, repeated, tag = "4")]
    pub acks: ::prost::alloc::vec::Vec<ack_message_request::Message>,
}
/// Nested message and enum types in `AckMessageRequest`.
pub mod ack_message_request {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(message_name = "client.AckMessageRequest.Message")]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Message {
        #[prost(string, tag = "1")]
        pub request_id: ::prost::alloc::string::String,
        #[prost(message, optional, tag = "2")]
        pub device: ::core::option::Option<super::super::authentication::Device>,
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.DownloadAttachmentRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DownloadAttachmentRequest {
    #[prost(message, optional, tag = "1")]
    pub info: ::core::option::Option<AttachmentInfo>,
    #[prost(message, optional, tag = "2")]
    pub auth_data: ::core::option::Option<super::authentication::AuthMessage>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.AttachmentInfo")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AttachmentInfo {
    #[prost(string, tag = "1")]
    pub attachment_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub encrypted: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.StartMediaUploadRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartMediaUploadRequest {
    #[prost(int64, tag = "1")]
    pub attachment_type: i64,
    #[prost(message, optional, tag = "2")]
    pub auth_data: ::core::option::Option<super::authentication::AuthMessage>,
    #[prost(message, optional, tag = "3")]
    pub mobile: ::core::option::Option<super::authentication::Device>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.UploadMediaResponse")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UploadMediaResponse {
    #[prost(message, optional, tag = "1")]
    pub media: ::core::option::Option<UploadedMedia>,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.UploadedMedia")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UploadedMedia {
    #[prost(string, tag = "1")]
    pub media_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub media_number: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.GetThumbnailRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetThumbnailRequest {
    #[prost(string, repeated, tag = "1")]
    pub identifiers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.GetThumbnailResponse")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetThumbnailResponse {
    #[prost(message, repeated, tag = "1")]
    pub thumbnail: ::prost::alloc::vec::Vec<get_thumbnail_response::Thumbnail>,
}
/// Nested message and enum types in `GetThumbnailResponse`.
pub mod get_thumbnail_response {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(message_name = "client.GetThumbnailResponse.Thumbnail")]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Thumbnail {
        /// ID depends on request, it's always the same as the input.
        #[prost(string, tag = "1")]
        pub identifier: ::prost::alloc::string::String,
        #[prost(message, optional, tag = "2")]
        pub data: ::core::option::Option<super::ThumbnailData>,
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.ThumbnailData")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ThumbnailData {
    /// 2 -> 13: 16 mysterious bytes
    #[prost(bytes = "vec", tag = "3")]
    pub image_buffer: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag = "4")]
    pub some_int: i32,
    #[prost(message, optional, tag = "5")]
    pub dimensions: ::core::option::Option<super::conversations::Dimensions>,
    #[prost(message, optional, tag = "2")]
    pub mysterious_data: ::core::option::Option<thumbnail_data::MysteriousData>,
}
/// Nested message and enum types in `ThumbnailData`.
pub mod thumbnail_data {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(message_name = "client.ThumbnailData.MysteriousData")]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct MysteriousData {
        #[prost(fixed64, tag = "13")]
        pub maybe_a_hash: u64,
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.Cursor")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Cursor {
    #[prost(string, tag = "1")]
    pub last_item_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub last_item_timestamp: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.ListMessagesRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListMessagesRequest {
    #[prost(string, tag = "2")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub count: i64,
    #[prost(message, optional, tag = "5")]
    pub cursor: ::core::option::Option<Cursor>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.ListMessagesResponse")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListMessagesResponse {
    #[prost(message, repeated, tag = "2")]
    pub messages: ::prost::alloc::vec::Vec<super::conversations::Message>,
    #[prost(bytes = "vec", tag = "3")]
    pub some_bytes: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "4")]
    pub total_messages: i64,
    #[prost(message, optional, tag = "5")]
    pub cursor: ::core::option::Option<Cursor>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.ListContactsRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListContactsRequest {
    /// = 1
    #[prost(int32, tag = "5")]
    pub i1: i32,
    /// = 350
    #[prost(int32, tag = "6")]
    pub i2: i32,
    /// = 50
    #[prost(int32, tag = "7")]
    pub i3: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.ListTopContactsRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListTopContactsRequest {
    #[prost(int32, tag = "1")]
    pub count: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.ListContactsResponse")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListContactsResponse {
    #[prost(message, repeated, tag = "2")]
    pub contacts: ::prost::alloc::vec::Vec<super::conversations::Contact>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.ListTopContactsResponse")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTopContactsResponse {
    #[prost(message, repeated, tag = "1")]
    pub contacts: ::prost::alloc::vec::Vec<super::conversations::Contact>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.ListConversationsRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListConversationsRequest {
    #[prost(int64, tag = "2")]
    pub count: i64,
    #[prost(enumeration = "list_conversations_request::Folder", tag = "4")]
    pub folder: i32,
    #[prost(message, optional, tag = "5")]
    pub cursor: ::core::option::Option<Cursor>,
}
/// Nested message and enum types in `ListConversationsRequest`.
pub mod list_conversations_request {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Folder {
        Unknown = 0,
        Inbox = 1,
        Archive = 2,
        SpamBlocked = 5,
    }
    impl Folder {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unknown => "UNKNOWN",
                Self::Inbox => "INBOX",
                Self::Archive => "ARCHIVE",
                Self::SpamBlocked => "SPAM_BLOCKED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNKNOWN" => Some(Self::Unknown),
                "INBOX" => Some(Self::Inbox),
                "ARCHIVE" => Some(Self::Archive),
                "SPAM_BLOCKED" => Some(Self::SpamBlocked),
                _ => None,
            }
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.ListConversationsResponse")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListConversationsResponse {
    #[prost(message, repeated, tag = "2")]
    pub conversations: ::prost::alloc::vec::Vec<super::conversations::Conversation>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub cursor_bytes: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, optional, tag = "5")]
    pub cursor: ::core::option::Option<Cursor>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.GetOrCreateConversationRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetOrCreateConversationRequest {
    #[prost(message, repeated, tag = "2")]
    pub numbers: ::prost::alloc::vec::Vec<super::conversations::ContactNumber>,
    #[prost(string, optional, tag = "3")]
    pub rcs_group_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "4")]
    pub create_rcs_group: ::core::option::Option<bool>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.GetOrCreateConversationResponse")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetOrCreateConversationResponse {
    #[prost(message, optional, tag = "2")]
    pub conversation: ::core::option::Option<super::conversations::Conversation>,
    #[prost(enumeration = "get_or_create_conversation_response::Status", tag = "3")]
    pub status: i32,
}
/// Nested message and enum types in `GetOrCreateConversationResponse`.
pub mod get_or_create_conversation_response {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Status {
        Unknown = 0,
        Success = 1,
        CreateRcs = 3,
    }
    impl Status {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unknown => "UNKNOWN",
                Self::Success => "SUCCESS",
                Self::CreateRcs => "CREATE_RCS",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNKNOWN" => Some(Self::Unknown),
                "SUCCESS" => Some(Self::Success),
                "CREATE_RCS" => Some(Self::CreateRcs),
                _ => None,
            }
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.DeleteMessageRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteMessageRequest {
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.DeleteMessageResponse")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteMessageResponse {
    #[prost(bool, tag = "2")]
    pub success: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.UpdateConversationRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateConversationRequest {
    #[prost(enumeration = "ConversationActionStatus", tag = "2")]
    pub action: i32,
    #[prost(string, tag = "3")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub action5: ::core::option::Option<ConversationAction5>,
    #[prost(oneof = "update_conversation_request::Data", tags = "6, 1")]
    pub data: ::core::option::Option<update_conversation_request::Data>,
}
/// Nested message and enum types in `UpdateConversationRequest`.
pub mod update_conversation_request {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "6")]
        DeleteData(super::DeleteConversationData),
        #[prost(message, tag = "1")]
        UpdateData(super::UpdateConversationData),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.ConversationAction5")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConversationAction5 {
    #[prost(bool, tag = "2")]
    pub field2: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.DeleteConversationData")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteConversationData {
    #[prost(string, tag = "1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub phone: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.UpdateConversationData")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateConversationData {
    #[prost(string, tag = "1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(oneof = "update_conversation_data::Data", tags = "12, 7")]
    pub data: ::core::option::Option<update_conversation_data::Data>,
}
/// Nested message and enum types in `UpdateConversationData`.
pub mod update_conversation_data {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Data {
        #[prost(
            enumeration = "super::super::conversations::ConversationStatus",
            tag = "12"
        )]
        Status(i32),
        #[prost(enumeration = "super::ConversationMuteStatus", tag = "7")]
        Mute(i32),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.UpdateConversationResponse")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateConversationResponse {
    ///
    /// 3 {
    /// 1 {
    /// 1 {
    /// 3: "11"
    /// }
    /// 13: 2
    /// }
    /// 3: 1
    /// }
    #[prost(bool, tag = "1")]
    pub success: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.GetConversationTypeRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetConversationTypeRequest {
    #[prost(string, tag = "2")]
    pub conversation_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.GetConversationTypeResponse")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetConversationTypeResponse {
    #[prost(string, tag = "2")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub r#type: i32,
    #[prost(bool, tag = "5")]
    pub bool1: bool,
    #[prost(int32, tag = "6")]
    pub number2: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.GetConversationRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetConversationRequest {
    #[prost(string, tag = "1")]
    pub conversation_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.GetConversationResponse")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationResponse {
    #[prost(message, optional, tag = "1")]
    pub conversation: ::core::option::Option<super::conversations::Conversation>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.OpenConversationRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OpenConversationRequest {
    #[prost(string, tag = "2")]
    pub conversation_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.PrepareOpenConversationRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PrepareOpenConversationRequest {
    /// only seen value 1
    #[prost(int64, tag = "2")]
    pub field2: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.IsBugleDefaultResponse")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IsBugleDefaultResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.SendMessageRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendMessageRequest {
    #[prost(string, tag = "2")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub message_payload: ::core::option::Option<MessagePayload>,
    #[prost(message, optional, tag = "4")]
    pub sim_payload: ::core::option::Option<super::settings::SimPayload>,
    #[prost(string, tag = "5")]
    pub tmp_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub force_rcs: bool,
    #[prost(message, optional, tag = "8")]
    pub reply: ::core::option::Option<ReplyPayload>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.ReplyPayload")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplyPayload {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.MessagePayload")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessagePayload {
    #[prost(string, tag = "1")]
    pub tmp_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "6")]
    pub message_payload_content: ::core::option::Option<MessagePayloadContent>,
    #[prost(string, tag = "7")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub participant_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "10")]
    pub message_info: ::prost::alloc::vec::Vec<super::conversations::MessageInfo>,
    #[prost(string, tag = "12")]
    pub tmp_id2: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.MessagePayloadContent")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessagePayloadContent {
    #[prost(message, optional, tag = "1")]
    pub message_content: ::core::option::Option<super::conversations::MessageContent>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.SendMessageResponse")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendMessageResponse {
    #[prost(message, optional, tag = "2")]
    pub google_account_switch: ::core::option::Option<
        super::events::AccountChangeOrSomethingEvent,
    >,
    #[prost(enumeration = "send_message_response::Status", tag = "3")]
    pub status: i32,
}
/// Nested message and enum types in `SendMessageResponse`.
pub mod send_message_response {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Status {
        Unknown = 0,
        Success = 1,
        Failure2 = 2,
        Failure3 = 3,
        /// not default sms app?
        Failure4 = 4,
    }
    impl Status {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unknown => "UNKNOWN",
                Self::Success => "SUCCESS",
                Self::Failure2 => "FAILURE_2",
                Self::Failure3 => "FAILURE_3",
                Self::Failure4 => "FAILURE_4",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNKNOWN" => Some(Self::Unknown),
                "SUCCESS" => Some(Self::Success),
                "FAILURE_2" => Some(Self::Failure2),
                "FAILURE_3" => Some(Self::Failure3),
                "FAILURE_4" => Some(Self::Failure4),
                _ => None,
            }
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.SendReactionRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendReactionRequest {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub reaction_data: ::core::option::Option<super::conversations::ReactionData>,
    #[prost(enumeration = "send_reaction_request::Action", tag = "3")]
    pub action: i32,
    #[prost(message, optional, tag = "4")]
    pub sim_payload: ::core::option::Option<super::settings::SimPayload>,
}
/// Nested message and enum types in `SendReactionRequest`.
pub mod send_reaction_request {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Action {
        Unspecified = 0,
        Add = 1,
        Remove = 2,
        Switch = 3,
    }
    impl Action {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "UNSPECIFIED",
                Self::Add => "ADD",
                Self::Remove => "REMOVE",
                Self::Switch => "SWITCH",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNSPECIFIED" => Some(Self::Unspecified),
                "ADD" => Some(Self::Add),
                "REMOVE" => Some(Self::Remove),
                "SWITCH" => Some(Self::Switch),
                _ => None,
            }
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.SendReactionResponse")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendReactionResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.ResendMessageRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResendMessageRequest {
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.TypingUpdateRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TypingUpdateRequest {
    #[prost(message, optional, tag = "2")]
    pub data: ::core::option::Option<typing_update_request::Data>,
    #[prost(message, optional, tag = "3")]
    pub sim_payload: ::core::option::Option<super::settings::SimPayload>,
}
/// Nested message and enum types in `TypingUpdateRequest`.
pub mod typing_update_request {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(message_name = "client.TypingUpdateRequest.Data")]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Data {
        #[prost(string, tag = "1")]
        pub conversation_id: ::prost::alloc::string::String,
        #[prost(bool, tag = "3")]
        pub typing: bool,
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.SettingsUpdateRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SettingsUpdateRequest {
    #[prost(message, optional, tag = "3")]
    pub push_settings: ::core::option::Option<settings_update_request::PushSettings>,
}
/// Nested message and enum types in `SettingsUpdateRequest`.
pub mod settings_update_request {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(message_name = "client.SettingsUpdateRequest.PushSettings")]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct PushSettings {
        #[prost(bool, tag = "3")]
        pub enabled: bool,
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.GetFullSizeImageRequest")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetFullSizeImageRequest {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub action_message_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "client.GetFullSizeImageResponse")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetFullSizeImageResponse {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ConversationActionStatus {
    UnknownActionStatus = 0,
    Delete = 1,
    Unblock = 2,
    Block = 7,
    BlockAndReport = 8,
}
impl ConversationActionStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UnknownActionStatus => "UNKNOWN_ACTION_STATUS",
            Self::Delete => "DELETE",
            Self::Unblock => "UNBLOCK",
            Self::Block => "BLOCK",
            Self::BlockAndReport => "BLOCK_AND_REPORT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_ACTION_STATUS" => Some(Self::UnknownActionStatus),
            "DELETE" => Some(Self::Delete),
            "UNBLOCK" => Some(Self::Unblock),
            "BLOCK" => Some(Self::Block),
            "BLOCK_AND_REPORT" => Some(Self::BlockAndReport),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ConversationMuteStatus {
    Unmute = 0,
    Mute = 1,
}
impl ConversationMuteStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unmute => "UNMUTE",
            Self::Mute => "MUTE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNMUTE" => Some(Self::Unmute),
            "MUTE" => Some(Self::Mute),
            _ => None,
        }
    }
}
