// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "config.Config")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Config {
    #[prost(string, tag = "1")]
    pub client_version: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub server_version: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub int_flags: ::prost::alloc::vec::Vec<config::Flag>,
    #[prost(message, optional, tag = "4")]
    pub more_flags: ::core::option::Option<config::MoreFlags>,
    #[prost(message, optional, tag = "5")]
    pub device_info: ::core::option::Option<config::DeviceInfo>,
    /// item 6 seems like a list of device infos without device ID?
    #[prost(string, tag = "7")]
    pub country_code: ::prost::alloc::string::String,
    #[prost(uint32, repeated, tag = "8")]
    pub unknown_ints: ::prost::alloc::vec::Vec<u32>,
    #[prost(int64, tag = "9")]
    pub generated_at_ms: i64,
}
/// Nested message and enum types in `Config`.
pub mod config {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(message_name = "config.Config.Flag")]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Flag {
        #[prost(string, tag = "1")]
        pub key: ::prost::alloc::string::String,
        #[prost(int32, tag = "2")]
        pub value: i32,
        #[prost(string, optional, tag = "4")]
        pub unknown_field4: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "5")]
        pub unknown_field5: ::core::option::Option<::prost::alloc::string::String>,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(message_name = "config.Config.WrappedFlag")]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct WrappedFlag {
        #[prost(string, tag = "1")]
        pub key: ::prost::alloc::string::String,
        #[prost(message, optional, tag = "2")]
        pub value: ::core::option::Option<wrapped_flag::Value>,
    }
    /// Nested message and enum types in `WrappedFlag`.
    pub mod wrapped_flag {
        #[derive(serde::Serialize, serde::Deserialize)]
        #[derive(::prost_reflect::ReflectMessage)]
        #[prost_reflect(message_name = "config.Config.WrappedFlag.Value")]
        #[prost_reflect(
            file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
        )]
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct Value {
            #[prost(oneof = "value::Value", tags = "2, 3")]
            pub value: ::core::option::Option<value::Value>,
        }
        /// Nested message and enum types in `Value`.
        pub mod value {
            #[derive(serde::Serialize, serde::Deserialize)]
            #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
            pub enum Value {
                #[prost(int32, tag = "2")]
                IntVal(i32),
                #[prost(string, tag = "3")]
                StrVal(::prost::alloc::string::String),
            }
        }
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(message_name = "config.Config.MoreFlags")]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct MoreFlags {
        #[prost(message, repeated, tag = "1")]
        pub wrapped_flags: ::prost::alloc::vec::Vec<WrappedFlag>,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(message_name = "config.Config.DeviceInfo")]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct DeviceInfo {
        #[prost(string, tag = "2")]
        pub email: ::prost::alloc::string::String,
        #[prost(string, tag = "3")]
        pub zero: ::prost::alloc::string::String,
        #[prost(string, tag = "4")]
        pub device_id: ::prost::alloc::string::String,
    }
}
