// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "conversations.Contact")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Contact {
    #[prost(string, tag = "1")]
    pub participant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub number: ::core::option::Option<ContactNumber>,
    #[prost(string, tag = "7")]
    pub avatar_hex_color: ::prost::alloc::string::String,
    #[prost(bool, tag = "10")]
    pub unknown_bool: bool,
    #[prost(string, tag = "11")]
    pub contact_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "conversations.ContactNumber")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ContactNumber {
    /// Might be 2 for contact and 7 for user input?
    #[prost(int32, tag = "1")]
    pub mysterious_int: i32,
    #[prost(string, tag = "2")]
    pub number: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub number2: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "4")]
    pub formatted_number: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "conversations.SomeKindOfGroupID")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SomeKindOfGroupId {
    #[prost(string, tag = "1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub nested_id: ::core::option::Option<some_kind_of_group_id::NestedId>,
}
/// Nested message and enum types in `SomeKindOfGroupID`.
pub mod some_kind_of_group_id {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(message_name = "conversations.SomeKindOfGroupID.NestedID")]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct NestedId {
        #[prost(string, tag = "1")]
        pub id: ::prost::alloc::string::String,
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "conversations.AnotherMessageID")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AnotherMessageId {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub another_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "conversations.Message")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub msg_type: ::core::option::Option<MsgType>,
    #[prost(message, optional, tag = "4")]
    pub message_status: ::core::option::Option<MessageStatus>,
    /// check this
    #[prost(int64, tag = "5")]
    pub timestamp: i64,
    #[prost(string, tag = "7")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub participant_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "10")]
    pub message_info: ::prost::alloc::vec::Vec<MessageInfo>,
    /// 1 = sms, 2 = downloaded mms, 3 = undownloaded mms, 4 = rcs?
    #[prost(int64, tag = "11")]
    pub r#type: i64,
    #[prost(string, tag = "12")]
    pub tmp_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "14")]
    pub subject: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int64, tag = "16")]
    pub some_int: i64,
    #[prost(message, repeated, tag = "19")]
    pub reactions: ::prost::alloc::vec::Vec<ReactionEntry>,
    #[prost(message, optional, tag = "21")]
    pub reply_message: ::core::option::Option<ReplyMessage>,
    #[prost(message, optional, tag = "23")]
    pub some_kind_of_group_id: ::core::option::Option<SomeKindOfGroupId>,
    #[prost(message, optional, tag = "24")]
    pub another_message_id: ::core::option::Option<AnotherMessageId>,
    #[prost(message, optional, tag = "25")]
    pub sender_participant: ::core::option::Option<Participant>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "conversations.ReactionEntry")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReactionEntry {
    #[prost(message, optional, tag = "1")]
    pub data: ::core::option::Option<ReactionData>,
    #[prost(string, repeated, tag = "2")]
    pub participant_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "conversations.CustomEmojiData")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CustomEmojiData {
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
    #[prost(int32, optional, tag = "4")]
    pub unknown_int4: ::core::option::Option<i32>,
    #[prost(message, optional, tag = "100")]
    pub inner_data: ::core::option::Option<custom_emoji_data::Inner>,
}
/// Nested message and enum types in `CustomEmojiData`.
pub mod custom_emoji_data {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(message_name = "conversations.CustomEmojiData.Inner")]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Inner {
        #[prost(string, optional, tag = "100")]
        pub unknown_string: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(message, optional, tag = "101")]
        pub first: ::core::option::Option<inner::ImageData>,
        #[prost(message, optional, tag = "102")]
        pub second: ::core::option::Option<inner::WrappedImageData>,
    }
    /// Nested message and enum types in `Inner`.
    pub mod inner {
        #[derive(serde::Serialize, serde::Deserialize)]
        #[derive(::prost_reflect::ReflectMessage)]
        #[prost_reflect(message_name = "conversations.CustomEmojiData.Inner.ImageData")]
        #[prost_reflect(
            file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
        )]
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct ImageData {
            #[prost(string, tag = "1")]
            pub mime_type: ::prost::alloc::string::String,
            #[prost(string, tag = "2")]
            pub uri: ::prost::alloc::string::String,
            #[prost(int32, optional, tag = "3")]
            pub unknown_int3: ::core::option::Option<i32>,
            #[prost(string, optional, tag = "5")]
            pub unknown_string5: ::core::option::Option<::prost::alloc::string::String>,
        }
        #[derive(serde::Serialize, serde::Deserialize)]
        #[derive(::prost_reflect::ReflectMessage)]
        #[prost_reflect(
            message_name = "conversations.CustomEmojiData.Inner.WrappedImageData"
        )]
        #[prost_reflect(
            file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
        )]
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct WrappedImageData {
            #[prost(message, optional, tag = "1")]
            pub data: ::core::option::Option<wrapped_image_data::ImageData>,
        }
        /// Nested message and enum types in `WrappedImageData`.
        pub mod wrapped_image_data {
            #[derive(serde::Serialize, serde::Deserialize)]
            #[derive(::prost_reflect::ReflectMessage)]
            #[prost_reflect(
                message_name = "conversations.CustomEmojiData.Inner.WrappedImageData.ImageData"
            )]
            #[prost_reflect(
                file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
            )]
            #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
            pub struct ImageData {
                #[prost(int32, tag = "1")]
                pub unknown_int1: i32,
                #[prost(string, tag = "2")]
                pub mime_type: ::prost::alloc::string::String,
                #[prost(string, tag = "3")]
                pub uri: ::prost::alloc::string::String,
                #[prost(int32, tag = "5")]
                pub width: i32,
                #[prost(int32, tag = "6")]
                pub height: i32,
                #[prost(int32, optional, tag = "7")]
                pub unknown_int7: ::core::option::Option<i32>,
            }
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "conversations.ReactionData")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReactionData {
    #[prost(string, tag = "1")]
    pub unicode: ::prost::alloc::string::String,
    #[prost(enumeration = "EmojiType", tag = "2")]
    pub r#type: i32,
    #[prost(message, optional, tag = "101")]
    pub custom_emoji: ::core::option::Option<CustomEmojiData>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "conversations.EmojiMeta")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EmojiMeta {
    #[prost(message, repeated, tag = "1")]
    pub emoji_meta_data: ::prost::alloc::vec::Vec<EmojiMetaData>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "conversations.EmojiMetaData")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EmojiMetaData {
    #[prost(string, tag = "1")]
    pub unicode: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "conversations.ReplyMessage")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplyMessage {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    /// might be participantID
    #[prost(string, tag = "2")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub reply_message_data: ::core::option::Option<ReplyMessageData>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "conversations.ReplyMessageData")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplyMessageData {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "conversations.MessageInfo")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageInfo {
    #[prost(string, optional, tag = "1")]
    pub action_message_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(oneof = "message_info::Data", tags = "2, 3")]
    pub data: ::core::option::Option<message_info::Data>,
}
/// Nested message and enum types in `MessageInfo`.
pub mod message_info {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "2")]
        MessageContent(super::MessageContent),
        #[prost(message, tag = "3")]
        MediaContent(super::MediaContent),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "conversations.MediaContent")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MediaContent {
    #[prost(enumeration = "MediaFormats", tag = "1")]
    pub format: i32,
    #[prost(string, tag = "2")]
    pub media_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub media_name: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub size: i64,
    #[prost(message, optional, tag = "6")]
    pub dimensions: ::core::option::Option<Dimensions>,
    #[prost(bytes = "vec", tag = "7")]
    pub media_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "9")]
    pub thumbnail_media_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "11")]
    pub decryption_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "12")]
    pub thumbnail_decryption_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "14")]
    pub mime_type: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "conversations.Dimensions")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Dimensions {
    #[prost(int64, tag = "1")]
    pub width: i64,
    #[prost(int64, tag = "2")]
    pub height: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "conversations.MessageContent")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageContent {
    #[prost(string, tag = "1")]
    pub content: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "conversations.MsgType")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MsgType {
    #[prost(int64, tag = "1")]
    pub r#type: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "conversations.MessageStatus")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageStatus {
    #[prost(enumeration = "MessageStatusType", tag = "2")]
    pub status: i32,
    #[prost(int64, tag = "3")]
    pub sub_code: i64,
    #[prost(string, tag = "4")]
    pub err_msg: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub status_text: ::prost::alloc::string::String,
    #[prost(int64, tag = "6")]
    pub third_code: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "conversations.Conversation")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Conversation {
    #[prost(string, tag = "1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub latest_message: ::core::option::Option<LatestMessage>,
    #[prost(int64, tag = "5")]
    pub last_message_timestamp: i64,
    #[prost(bool, tag = "6")]
    pub unread: bool,
    /// not certain
    #[prost(bool, tag = "10")]
    pub is_group_chat: bool,
    #[prost(string, tag = "11")]
    pub default_outgoing_id: ::prost::alloc::string::String,
    #[prost(enumeration = "ConversationStatus", tag = "12")]
    pub status: i32,
    #[prost(bool, tag = "13")]
    pub read_only: bool,
    #[prost(string, tag = "15")]
    pub avatar_hex_color: ::prost::alloc::string::String,
    #[prost(string, tag = "17")]
    pub latest_message_id: ::prost::alloc::string::String,
    #[prost(enumeration = "ConversationSendMode", tag = "18")]
    pub send_mode: i32,
    #[prost(message, repeated, tag = "20")]
    pub participants: ::prost::alloc::vec::Vec<Participant>,
    /// participant ids excluding me
    #[prost(string, repeated, tag = "21")]
    pub other_participants: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(enumeration = "ConversationType", tag = "22")]
    pub r#type: i32,
    #[prost(bool, tag = "24")]
    pub sub_type: bool,
    #[prost(bool, tag = "26")]
    pub pinned: bool,
    /// set to lastMessageTimestamp + 1000 when marking as unread?
    #[prost(int64, tag = "28")]
    pub unknown_timestamp: i64,
    #[prost(bool, tag = "29")]
    pub third_type: bool,
    #[prost(message, optional, tag = "31")]
    pub some_kind_of_group_id: ::core::option::Option<SomeKindOfGroupId>,
    #[prost(message, optional, tag = "32")]
    pub sim_card: ::core::option::Option<super::settings::SimCard>,
    /// URL for group conversation icon (observed on RCS group chats).
    #[prost(string, tag = "34")]
    pub group_avatar_url: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "35")]
    pub latest_message_anoher_id: ::core::option::Option<AnotherMessageId>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "conversations.Participant")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Participant {
    #[prost(message, optional, tag = "1")]
    pub id: ::core::option::Option<SmallInfo>,
    #[prost(string, tag = "2")]
    pub first_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub full_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub avatar_hex_color: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub is_me: bool,
    #[prost(message, optional, tag = "7")]
    pub sim_payload: ::core::option::Option<super::settings::SimPayload>,
    #[prost(bool, tag = "8")]
    pub is_visible: bool,
    #[prost(string, tag = "10")]
    pub contact_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "14")]
    pub bs: i64,
    #[prost(string, tag = "15")]
    pub formatted_number: ::prost::alloc::string::String,
    #[prost(int64, tag = "19")]
    pub some_int1: i64,
    #[prost(int64, tag = "20")]
    pub some_int2: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "conversations.SmallInfo")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SmallInfo {
    #[prost(enumeration = "IdentifierType", tag = "1")]
    pub r#type: i32,
    #[prost(string, tag = "2")]
    pub number: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub participant_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "conversations.LatestMessage")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LatestMessage {
    #[prost(string, tag = "1")]
    pub display_content: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub from_me: i64,
    #[prost(string, tag = "4")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub latest_message_status: ::core::option::Option<LatestMessageStatus>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "conversations.LatestMessageStatus")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LatestMessageStatus {
    #[prost(int64, tag = "1")]
    pub status2: i64,
    #[prost(enumeration = "MessageStatusType", tag = "2")]
    pub status: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "conversations.Muted")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Muted {
    #[prost(int64, tag = "1")]
    pub is_muted: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EmojiType {
    ReactionTypeUnspecified = 0,
    Like = 1,
    Love = 2,
    Laugh = 3,
    Surprised = 4,
    Sad = 5,
    Angry = 6,
    Dislike = 7,
    Custom = 8,
    Questioning = 9,
    CryingFace = 10,
    PoutingFace = 11,
    RedHeart = 12,
    Emotify = 13,
}
impl EmojiType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::ReactionTypeUnspecified => "REACTION_TYPE_UNSPECIFIED",
            Self::Like => "LIKE",
            Self::Love => "LOVE",
            Self::Laugh => "LAUGH",
            Self::Surprised => "SURPRISED",
            Self::Sad => "SAD",
            Self::Angry => "ANGRY",
            Self::Dislike => "DISLIKE",
            Self::Custom => "CUSTOM",
            Self::Questioning => "QUESTIONING",
            Self::CryingFace => "CRYING_FACE",
            Self::PoutingFace => "POUTING_FACE",
            Self::RedHeart => "RED_HEART",
            Self::Emotify => "EMOTIFY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "REACTION_TYPE_UNSPECIFIED" => Some(Self::ReactionTypeUnspecified),
            "LIKE" => Some(Self::Like),
            "LOVE" => Some(Self::Love),
            "LAUGH" => Some(Self::Laugh),
            "SURPRISED" => Some(Self::Surprised),
            "SAD" => Some(Self::Sad),
            "ANGRY" => Some(Self::Angry),
            "DISLIKE" => Some(Self::Dislike),
            "CUSTOM" => Some(Self::Custom),
            "QUESTIONING" => Some(Self::Questioning),
            "CRYING_FACE" => Some(Self::CryingFace),
            "POUTING_FACE" => Some(Self::PoutingFace),
            "RED_HEART" => Some(Self::RedHeart),
            "EMOTIFY" => Some(Self::Emotify),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum IdentifierType {
    Unknown = 0,
    Phone = 1,
    Email = 2,
}
impl IdentifierType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "UNKNOWN",
            Self::Phone => "PHONE",
            Self::Email => "EMAIL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN" => Some(Self::Unknown),
            "PHONE" => Some(Self::Phone),
            "EMAIL" => Some(Self::Email),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ConversationSendMode {
    SendModeAuto = 0,
    SendModeXms = 1,
    SendModeXmsLatch = 2,
}
impl ConversationSendMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::SendModeAuto => "SEND_MODE_AUTO",
            Self::SendModeXms => "SEND_MODE_XMS",
            Self::SendModeXmsLatch => "SEND_MODE_XMS_LATCH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SEND_MODE_AUTO" => Some(Self::SendModeAuto),
            "SEND_MODE_XMS" => Some(Self::SendModeXms),
            "SEND_MODE_XMS_LATCH" => Some(Self::SendModeXmsLatch),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ConversationType {
    UnknownConversationType = 0,
    Sms = 1,
    Rcs = 2,
}
impl ConversationType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UnknownConversationType => "UNKNOWN_CONVERSATION_TYPE",
            Self::Sms => "SMS",
            Self::Rcs => "RCS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_CONVERSATION_TYPE" => Some(Self::UnknownConversationType),
            "SMS" => Some(Self::Sms),
            "RCS" => Some(Self::Rcs),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageStatusType {
    StatusUnknown = 0,
    OutgoingComplete = 1,
    OutgoingDelivered = 2,
    OutgoingDisplayed = 11,
    OutgoingDraft = 3,
    OutgoingSendAfterProcessing = 10,
    OutgoingYetToSend = 4,
    OutgoingSending = 5,
    OutgoingResending = 6,
    OutgoingAwaitingRetry = 7,
    OutgoingFailedGeneric = 8,
    OutgoingFailedEmergencyNumber = 9,
    OutgoingCanceled = 12,
    OutgoingFailedTooLarge = 13,
    OutgoingNotDeliveredYet = 14,
    OutgoingRevocationPending = 15,
    OutgoingScheduled = 16,
    OutgoingFailedRecipientLostRcs = 17,
    OutgoingFailedNoRetryNoFallback = 18,
    OutgoingFailedRecipientDidNotDecrypt = 19,
    OutgoingValidating = 20,
    OutgoingFailedRecipientLostEncryption = 21,
    OutgoingFailedRecipientDidNotDecryptNoMoreRetry = 22,
    IncomingComplete = 100,
    IncomingYetToManualDownload = 101,
    IncomingRetryingManualDownload = 102,
    IncomingManualDownloading = 103,
    IncomingRetryingAutoDownload = 104,
    IncomingAutoDownloading = 105,
    IncomingDownloadFailed = 106,
    IncomingExpiredOrNotAvailable = 107,
    IncomingDelivered = 108,
    IncomingDisplayed = 109,
    IncomingDownloadCanceled = 110,
    IncomingDownloadFailedTooLarge = 111,
    IncomingDownloadFailedSimHasNoData = 112,
    IncomingFailedToDecrypt = 113,
    IncomingDecryptionAborted = 114,
    TombstoneParticipantJoined = 200,
    TombstoneParticipantLeft = 201,
    TombstoneSelfLeft = 202,
    TombstoneRcsGroupCreated = 203,
    TombstoneMmsGroupCreated = 204,
    TombstoneSmsBroadcastCreated = 205,
    TombstoneOneOnOneSmsCreated = 206,
    TombstoneOneOnOneRcsCreated = 207,
    TombstoneSwitchToGroupMms = 208,
    TombstoneSwitchToBroadcastSms = 209,
    TombstoneShowLinkPreviews = 210,
    TombstoneGroupRenamedLocal = 211,
    TombstoneVerifiedSmsApplicable = 212,
    TombstoneEncryptedOneOnOneRcsCreated = 213,
    TombstoneProtocolSwitchToText = 214,
    TombstoneProtocolSwitchToRcs = 215,
    TombstoneProtocolSwitchToEncryptedRcs = 216,
    TombstoneGroupRenamedGlobal = 217,
    TombstoneGroupNameClearedGlobal = 218,
    TombstoneProtocolSwitchToEncryptedRcsInfo = 219,
    TombstoneSelfRemovedFromGroup = 220,
    MessageStatusTombstoneParticipantRemovedFromGroup = 221,
    MessageStatusTombstoneSmsNormParticipantUpgraded = 222,
    MessageStatusTombstoneRcsNormParticipantUpgraded = 223,
    MessageStatusTombstoneEncryptedRcsNormParticipantUpgraded = 224,
    MessageStatusTombstoneEncryptedGroupParticipantJoined = 225,
    MessageStatusTombstoneEncryptedGroupParticipantJoinedInfo = 226,
    MessageStatusTombstoneEncryptedGroupParticipantLeft = 227,
    MessageStatusTombstoneEncryptedGroupSelfLeft = 228,
    MessageStatusTombstoneEncryptedGroupCreated = 229,
    MessageStatusTombstoneSelfRemovedFromEncryptedGroup = 230,
    MessageStatusTombstoneParticipantRemovedFromEncryptedGroup = 231,
    MessageStatusTombstoneSuggestionShortcutStarToolstone = 232,
    MessageStatusTombstoneGroupProtocolSwitchRcsToE2ee = 233,
    MessageStatusTombstoneGroupProtocolSwitchE2eeToRcs = 234,
    MessageStatusTombstoneProtocolSwitchTextToE2ee = 235,
    MessageStatusTombstoneProtocolSwitchE2eeToText = 236,
    MessageStatusTombstoneProtocolSwitchRcsToE2ee = 237,
    MessageStatusTombstoneProtocolSwitchE2eeToRcs = 238,
    MessageStatusTombstoneSatelliteEducation = 239,
    MessageStatusTombstoneRbmSimSwitch = 240,
    MessageStatusTombstoneRbmPrivacyNotice = 241,
    MessageStatusTombstonePenpalConversationNotice = 242,
    MessageStatusTombstoneMeetOtherParticipantReachable = 243,
    MessageStatusTombstoneMissedVideoCall = 244,
    MessageStatusTombstoneParticipantThemeChange = 245,
    MessageStatusTombstoneSatelliteEndOfEmergencySuccessHelpStillNeeded = 246,
    MessageStatusTombstoneSatelliteEndOfEmergencySuccessHelpNoLongerNeeded = 247,
    MessageStatusTombstoneSatelliteEndOfEmergencyFailureHelpStillNeeded = 248,
    MessageStatusTombstoneSatelliteEndOfEmergencyFailureHelpNoLongerNeeded = 249,
    MessageStatusTombstoneSatelliteEndOfEmergencyUnexpectedEnd = 250,
    MessageStatusTombstoneSatelliteMessagingToolstone = 251,
    MessageStatusTombstoneGroupProtocolSwitchE2eeToMms = 252,
    MessageStatusTombstonePenpalProactiveMessageNotice = 253,
    MessageStatusTombstoneSuggestionPossibleScamToolstone = 254,
    MessageStatusTombstoneChatbotUnsubscribeSent = 255,
    MessageStatusTombstoneChatbotSubscribeSent = 256,
    MessageStatusTombstoneChatbotUnsubscribeConfirmed = 257,
    MessageStatusTombstoneChatbotSubscribeConfirmed = 258,
    MessageStatusTombstoneActiveSelfIdentityChanged = 259,
    MessageStatusTombstoneGroupIconChangedGlobal = 260,
    MessageStatusTombstoneGroupIconClearedGlobal = 261,
    MessageStatusTombstoneChatbotUnsubscribeError = 262,
    MessageStatusTombstoneChatbotSubscribeError = 263,
    MessageStatusTombstoneEmergencyConversationCreated = 264,
    MessageStatusTombstoneSensitiveContentWarningToolstone = 265,
    MessageStatusTombstoneChatbotUnsubscribeConfirmedNoLink = 266,
    MessageStatusTombstoneChatbotSubscribeConfirmedNoLink = 267,
    MessageStatusTombstoneEmergencyQuestionnaire = 268,
    MessageStatusTombstoneChatbotUnsubscribeSentNoLink = 269,
    MessageStatusTombstoneChatbotSubscribeSentNoLink = 270,
    MessageStatusTombstoneRcsGroupJoinedByLink = 271,
    MessageStatusTombstoneInviteLinkEnabled = 272,
    MessageStatusTombstoneInviteLinkDisabled = 273,
    MessageStatusTombstoneInviteLinkResetManually = 274,
    MessageStatusTombstoneInviteLinkResetAutomatically = 275,
    MessageDeleted = 300,
}
impl MessageStatusType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::StatusUnknown => "STATUS_UNKNOWN",
            Self::OutgoingComplete => "OUTGOING_COMPLETE",
            Self::OutgoingDelivered => "OUTGOING_DELIVERED",
            Self::OutgoingDisplayed => "OUTGOING_DISPLAYED",
            Self::OutgoingDraft => "OUTGOING_DRAFT",
            Self::OutgoingSendAfterProcessing => "OUTGOING_SEND_AFTER_PROCESSING",
            Self::OutgoingYetToSend => "OUTGOING_YET_TO_SEND",
            Self::OutgoingSending => "OUTGOING_SENDING",
            Self::OutgoingResending => "OUTGOING_RESENDING",
            Self::OutgoingAwaitingRetry => "OUTGOING_AWAITING_RETRY",
            Self::OutgoingFailedGeneric => "OUTGOING_FAILED_GENERIC",
            Self::OutgoingFailedEmergencyNumber => "OUTGOING_FAILED_EMERGENCY_NUMBER",
            Self::OutgoingCanceled => "OUTGOING_CANCELED",
            Self::OutgoingFailedTooLarge => "OUTGOING_FAILED_TOO_LARGE",
            Self::OutgoingNotDeliveredYet => "OUTGOING_NOT_DELIVERED_YET",
            Self::OutgoingRevocationPending => "OUTGOING_REVOCATION_PENDING",
            Self::OutgoingScheduled => "OUTGOING_SCHEDULED",
            Self::OutgoingFailedRecipientLostRcs => "OUTGOING_FAILED_RECIPIENT_LOST_RCS",
            Self::OutgoingFailedNoRetryNoFallback => {
                "OUTGOING_FAILED_NO_RETRY_NO_FALLBACK"
            }
            Self::OutgoingFailedRecipientDidNotDecrypt => {
                "OUTGOING_FAILED_RECIPIENT_DID_NOT_DECRYPT"
            }
            Self::OutgoingValidating => "OUTGOING_VALIDATING",
            Self::OutgoingFailedRecipientLostEncryption => {
                "OUTGOING_FAILED_RECIPIENT_LOST_ENCRYPTION"
            }
            Self::OutgoingFailedRecipientDidNotDecryptNoMoreRetry => {
                "OUTGOING_FAILED_RECIPIENT_DID_NOT_DECRYPT_NO_MORE_RETRY"
            }
            Self::IncomingComplete => "INCOMING_COMPLETE",
            Self::IncomingYetToManualDownload => "INCOMING_YET_TO_MANUAL_DOWNLOAD",
            Self::IncomingRetryingManualDownload => "INCOMING_RETRYING_MANUAL_DOWNLOAD",
            Self::IncomingManualDownloading => "INCOMING_MANUAL_DOWNLOADING",
            Self::IncomingRetryingAutoDownload => "INCOMING_RETRYING_AUTO_DOWNLOAD",
            Self::IncomingAutoDownloading => "INCOMING_AUTO_DOWNLOADING",
            Self::IncomingDownloadFailed => "INCOMING_DOWNLOAD_FAILED",
            Self::IncomingExpiredOrNotAvailable => "INCOMING_EXPIRED_OR_NOT_AVAILABLE",
            Self::IncomingDelivered => "INCOMING_DELIVERED",
            Self::IncomingDisplayed => "INCOMING_DISPLAYED",
            Self::IncomingDownloadCanceled => "INCOMING_DOWNLOAD_CANCELED",
            Self::IncomingDownloadFailedTooLarge => "INCOMING_DOWNLOAD_FAILED_TOO_LARGE",
            Self::IncomingDownloadFailedSimHasNoData => {
                "INCOMING_DOWNLOAD_FAILED_SIM_HAS_NO_DATA"
            }
            Self::IncomingFailedToDecrypt => "INCOMING_FAILED_TO_DECRYPT",
            Self::IncomingDecryptionAborted => "INCOMING_DECRYPTION_ABORTED",
            Self::TombstoneParticipantJoined => "TOMBSTONE_PARTICIPANT_JOINED",
            Self::TombstoneParticipantLeft => "TOMBSTONE_PARTICIPANT_LEFT",
            Self::TombstoneSelfLeft => "TOMBSTONE_SELF_LEFT",
            Self::TombstoneRcsGroupCreated => "TOMBSTONE_RCS_GROUP_CREATED",
            Self::TombstoneMmsGroupCreated => "TOMBSTONE_MMS_GROUP_CREATED",
            Self::TombstoneSmsBroadcastCreated => "TOMBSTONE_SMS_BROADCAST_CREATED",
            Self::TombstoneOneOnOneSmsCreated => "TOMBSTONE_ONE_ON_ONE_SMS_CREATED",
            Self::TombstoneOneOnOneRcsCreated => "TOMBSTONE_ONE_ON_ONE_RCS_CREATED",
            Self::TombstoneSwitchToGroupMms => "TOMBSTONE_SWITCH_TO_GROUP_MMS",
            Self::TombstoneSwitchToBroadcastSms => "TOMBSTONE_SWITCH_TO_BROADCAST_SMS",
            Self::TombstoneShowLinkPreviews => "TOMBSTONE_SHOW_LINK_PREVIEWS",
            Self::TombstoneGroupRenamedLocal => "TOMBSTONE_GROUP_RENAMED_LOCAL",
            Self::TombstoneVerifiedSmsApplicable => "TOMBSTONE_VERIFIED_SMS_APPLICABLE",
            Self::TombstoneEncryptedOneOnOneRcsCreated => {
                "TOMBSTONE_ENCRYPTED_ONE_ON_ONE_RCS_CREATED"
            }
            Self::TombstoneProtocolSwitchToText => "TOMBSTONE_PROTOCOL_SWITCH_TO_TEXT",
            Self::TombstoneProtocolSwitchToRcs => "TOMBSTONE_PROTOCOL_SWITCH_TO_RCS",
            Self::TombstoneProtocolSwitchToEncryptedRcs => {
                "TOMBSTONE_PROTOCOL_SWITCH_TO_ENCRYPTED_RCS"
            }
            Self::TombstoneGroupRenamedGlobal => "TOMBSTONE_GROUP_RENAMED_GLOBAL",
            Self::TombstoneGroupNameClearedGlobal => {
                "TOMBSTONE_GROUP_NAME_CLEARED_GLOBAL"
            }
            Self::TombstoneProtocolSwitchToEncryptedRcsInfo => {
                "TOMBSTONE_PROTOCOL_SWITCH_TO_ENCRYPTED_RCS_INFO"
            }
            Self::TombstoneSelfRemovedFromGroup => "TOMBSTONE_SELF_REMOVED_FROM_GROUP",
            Self::MessageStatusTombstoneParticipantRemovedFromGroup => {
                "MESSAGE_STATUS_TOMBSTONE_PARTICIPANT_REMOVED_FROM_GROUP"
            }
            Self::MessageStatusTombstoneSmsNormParticipantUpgraded => {
                "MESSAGE_STATUS_TOMBSTONE_SMS_NORM_PARTICIPANT_UPGRADED"
            }
            Self::MessageStatusTombstoneRcsNormParticipantUpgraded => {
                "MESSAGE_STATUS_TOMBSTONE_RCS_NORM_PARTICIPANT_UPGRADED"
            }
            Self::MessageStatusTombstoneEncryptedRcsNormParticipantUpgraded => {
                "MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_RCS_NORM_PARTICIPANT_UPGRADED"
            }
            Self::MessageStatusTombstoneEncryptedGroupParticipantJoined => {
                "MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_PARTICIPANT_JOINED"
            }
            Self::MessageStatusTombstoneEncryptedGroupParticipantJoinedInfo => {
                "MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_PARTICIPANT_JOINED_INFO"
            }
            Self::MessageStatusTombstoneEncryptedGroupParticipantLeft => {
                "MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_PARTICIPANT_LEFT"
            }
            Self::MessageStatusTombstoneEncryptedGroupSelfLeft => {
                "MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_SELF_LEFT"
            }
            Self::MessageStatusTombstoneEncryptedGroupCreated => {
                "MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_CREATED"
            }
            Self::MessageStatusTombstoneSelfRemovedFromEncryptedGroup => {
                "MESSAGE_STATUS_TOMBSTONE_SELF_REMOVED_FROM_ENCRYPTED_GROUP"
            }
            Self::MessageStatusTombstoneParticipantRemovedFromEncryptedGroup => {
                "MESSAGE_STATUS_TOMBSTONE_PARTICIPANT_REMOVED_FROM_ENCRYPTED_GROUP"
            }
            Self::MessageStatusTombstoneSuggestionShortcutStarToolstone => {
                "MESSAGE_STATUS_TOMBSTONE_SUGGESTION_SHORTCUT_STAR_TOOLSTONE"
            }
            Self::MessageStatusTombstoneGroupProtocolSwitchRcsToE2ee => {
                "MESSAGE_STATUS_TOMBSTONE_GROUP_PROTOCOL_SWITCH_RCS_TO_E2EE"
            }
            Self::MessageStatusTombstoneGroupProtocolSwitchE2eeToRcs => {
                "MESSAGE_STATUS_TOMBSTONE_GROUP_PROTOCOL_SWITCH_E2EE_TO_RCS"
            }
            Self::MessageStatusTombstoneProtocolSwitchTextToE2ee => {
                "MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_TEXT_TO_E2EE"
            }
            Self::MessageStatusTombstoneProtocolSwitchE2eeToText => {
                "MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_E2EE_TO_TEXT"
            }
            Self::MessageStatusTombstoneProtocolSwitchRcsToE2ee => {
                "MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_RCS_TO_E2EE"
            }
            Self::MessageStatusTombstoneProtocolSwitchE2eeToRcs => {
                "MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_E2EE_TO_RCS"
            }
            Self::MessageStatusTombstoneSatelliteEducation => {
                "MESSAGE_STATUS_TOMBSTONE_SATELLITE_EDUCATION"
            }
            Self::MessageStatusTombstoneRbmSimSwitch => {
                "MESSAGE_STATUS_TOMBSTONE_RBM_SIM_SWITCH"
            }
            Self::MessageStatusTombstoneRbmPrivacyNotice => {
                "MESSAGE_STATUS_TOMBSTONE_RBM_PRIVACY_NOTICE"
            }
            Self::MessageStatusTombstonePenpalConversationNotice => {
                "MESSAGE_STATUS_TOMBSTONE_PENPAL_CONVERSATION_NOTICE"
            }
            Self::MessageStatusTombstoneMeetOtherParticipantReachable => {
                "MESSAGE_STATUS_TOMBSTONE_MEET_OTHER_PARTICIPANT_REACHABLE"
            }
            Self::MessageStatusTombstoneMissedVideoCall => {
                "MESSAGE_STATUS_TOMBSTONE_MISSED_VIDEO_CALL"
            }
            Self::MessageStatusTombstoneParticipantThemeChange => {
                "MESSAGE_STATUS_TOMBSTONE_PARTICIPANT_THEME_CHANGE"
            }
            Self::MessageStatusTombstoneSatelliteEndOfEmergencySuccessHelpStillNeeded => {
                "MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_SUCCESS_HELP_STILL_NEEDED"
            }
            Self::MessageStatusTombstoneSatelliteEndOfEmergencySuccessHelpNoLongerNeeded => {
                "MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_SUCCESS_HELP_NO_LONGER_NEEDED"
            }
            Self::MessageStatusTombstoneSatelliteEndOfEmergencyFailureHelpStillNeeded => {
                "MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_FAILURE_HELP_STILL_NEEDED"
            }
            Self::MessageStatusTombstoneSatelliteEndOfEmergencyFailureHelpNoLongerNeeded => {
                "MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_FAILURE_HELP_NO_LONGER_NEEDED"
            }
            Self::MessageStatusTombstoneSatelliteEndOfEmergencyUnexpectedEnd => {
                "MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_UNEXPECTED_END"
            }
            Self::MessageStatusTombstoneSatelliteMessagingToolstone => {
                "MESSAGE_STATUS_TOMBSTONE_SATELLITE_MESSAGING_TOOLSTONE"
            }
            Self::MessageStatusTombstoneGroupProtocolSwitchE2eeToMms => {
                "MESSAGE_STATUS_TOMBSTONE_GROUP_PROTOCOL_SWITCH_E2EE_TO_MMS"
            }
            Self::MessageStatusTombstonePenpalProactiveMessageNotice => {
                "MESSAGE_STATUS_TOMBSTONE_PENPAL_PROACTIVE_MESSAGE_NOTICE"
            }
            Self::MessageStatusTombstoneSuggestionPossibleScamToolstone => {
                "MESSAGE_STATUS_TOMBSTONE_SUGGESTION_POSSIBLE_SCAM_TOOLSTONE"
            }
            Self::MessageStatusTombstoneChatbotUnsubscribeSent => {
                "MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_SENT"
            }
            Self::MessageStatusTombstoneChatbotSubscribeSent => {
                "MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_SENT"
            }
            Self::MessageStatusTombstoneChatbotUnsubscribeConfirmed => {
                "MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_CONFIRMED"
            }
            Self::MessageStatusTombstoneChatbotSubscribeConfirmed => {
                "MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_CONFIRMED"
            }
            Self::MessageStatusTombstoneActiveSelfIdentityChanged => {
                "MESSAGE_STATUS_TOMBSTONE_ACTIVE_SELF_IDENTITY_CHANGED"
            }
            Self::MessageStatusTombstoneGroupIconChangedGlobal => {
                "MESSAGE_STATUS_TOMBSTONE_GROUP_ICON_CHANGED_GLOBAL"
            }
            Self::MessageStatusTombstoneGroupIconClearedGlobal => {
                "MESSAGE_STATUS_TOMBSTONE_GROUP_ICON_CLEARED_GLOBAL"
            }
            Self::MessageStatusTombstoneChatbotUnsubscribeError => {
                "MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_ERROR"
            }
            Self::MessageStatusTombstoneChatbotSubscribeError => {
                "MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_ERROR"
            }
            Self::MessageStatusTombstoneEmergencyConversationCreated => {
                "MESSAGE_STATUS_TOMBSTONE_EMERGENCY_CONVERSATION_CREATED"
            }
            Self::MessageStatusTombstoneSensitiveContentWarningToolstone => {
                "MESSAGE_STATUS_TOMBSTONE_SENSITIVE_CONTENT_WARNING_TOOLSTONE"
            }
            Self::MessageStatusTombstoneChatbotUnsubscribeConfirmedNoLink => {
                "MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_CONFIRMED_NO_LINK"
            }
            Self::MessageStatusTombstoneChatbotSubscribeConfirmedNoLink => {
                "MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_CONFIRMED_NO_LINK"
            }
            Self::MessageStatusTombstoneEmergencyQuestionnaire => {
                "MESSAGE_STATUS_TOMBSTONE_EMERGENCY_QUESTIONNAIRE"
            }
            Self::MessageStatusTombstoneChatbotUnsubscribeSentNoLink => {
                "MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_SENT_NO_LINK"
            }
            Self::MessageStatusTombstoneChatbotSubscribeSentNoLink => {
                "MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_SENT_NO_LINK"
            }
            Self::MessageStatusTombstoneRcsGroupJoinedByLink => {
                "MESSAGE_STATUS_TOMBSTONE_RCS_GROUP_JOINED_BY_LINK"
            }
            Self::MessageStatusTombstoneInviteLinkEnabled => {
                "MESSAGE_STATUS_TOMBSTONE_INVITE_LINK_ENABLED"
            }
            Self::MessageStatusTombstoneInviteLinkDisabled => {
                "MESSAGE_STATUS_TOMBSTONE_INVITE_LINK_DISABLED"
            }
            Self::MessageStatusTombstoneInviteLinkResetManually => {
                "MESSAGE_STATUS_TOMBSTONE_INVITE_LINK_RESET_MANUALLY"
            }
            Self::MessageStatusTombstoneInviteLinkResetAutomatically => {
                "MESSAGE_STATUS_TOMBSTONE_INVITE_LINK_RESET_AUTOMATICALLY"
            }
            Self::MessageDeleted => "MESSAGE_DELETED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STATUS_UNKNOWN" => Some(Self::StatusUnknown),
            "OUTGOING_COMPLETE" => Some(Self::OutgoingComplete),
            "OUTGOING_DELIVERED" => Some(Self::OutgoingDelivered),
            "OUTGOING_DISPLAYED" => Some(Self::OutgoingDisplayed),
            "OUTGOING_DRAFT" => Some(Self::OutgoingDraft),
            "OUTGOING_SEND_AFTER_PROCESSING" => Some(Self::OutgoingSendAfterProcessing),
            "OUTGOING_YET_TO_SEND" => Some(Self::OutgoingYetToSend),
            "OUTGOING_SENDING" => Some(Self::OutgoingSending),
            "OUTGOING_RESENDING" => Some(Self::OutgoingResending),
            "OUTGOING_AWAITING_RETRY" => Some(Self::OutgoingAwaitingRetry),
            "OUTGOING_FAILED_GENERIC" => Some(Self::OutgoingFailedGeneric),
            "OUTGOING_FAILED_EMERGENCY_NUMBER" => {
                Some(Self::OutgoingFailedEmergencyNumber)
            }
            "OUTGOING_CANCELED" => Some(Self::OutgoingCanceled),
            "OUTGOING_FAILED_TOO_LARGE" => Some(Self::OutgoingFailedTooLarge),
            "OUTGOING_NOT_DELIVERED_YET" => Some(Self::OutgoingNotDeliveredYet),
            "OUTGOING_REVOCATION_PENDING" => Some(Self::OutgoingRevocationPending),
            "OUTGOING_SCHEDULED" => Some(Self::OutgoingScheduled),
            "OUTGOING_FAILED_RECIPIENT_LOST_RCS" => {
                Some(Self::OutgoingFailedRecipientLostRcs)
            }
            "OUTGOING_FAILED_NO_RETRY_NO_FALLBACK" => {
                Some(Self::OutgoingFailedNoRetryNoFallback)
            }
            "OUTGOING_FAILED_RECIPIENT_DID_NOT_DECRYPT" => {
                Some(Self::OutgoingFailedRecipientDidNotDecrypt)
            }
            "OUTGOING_VALIDATING" => Some(Self::OutgoingValidating),
            "OUTGOING_FAILED_RECIPIENT_LOST_ENCRYPTION" => {
                Some(Self::OutgoingFailedRecipientLostEncryption)
            }
            "OUTGOING_FAILED_RECIPIENT_DID_NOT_DECRYPT_NO_MORE_RETRY" => {
                Some(Self::OutgoingFailedRecipientDidNotDecryptNoMoreRetry)
            }
            "INCOMING_COMPLETE" => Some(Self::IncomingComplete),
            "INCOMING_YET_TO_MANUAL_DOWNLOAD" => Some(Self::IncomingYetToManualDownload),
            "INCOMING_RETRYING_MANUAL_DOWNLOAD" => {
                Some(Self::IncomingRetryingManualDownload)
            }
            "INCOMING_MANUAL_DOWNLOADING" => Some(Self::IncomingManualDownloading),
            "INCOMING_RETRYING_AUTO_DOWNLOAD" => Some(Self::IncomingRetryingAutoDownload),
            "INCOMING_AUTO_DOWNLOADING" => Some(Self::IncomingAutoDownloading),
            "INCOMING_DOWNLOAD_FAILED" => Some(Self::IncomingDownloadFailed),
            "INCOMING_EXPIRED_OR_NOT_AVAILABLE" => {
                Some(Self::IncomingExpiredOrNotAvailable)
            }
            "INCOMING_DELIVERED" => Some(Self::IncomingDelivered),
            "INCOMING_DISPLAYED" => Some(Self::IncomingDisplayed),
            "INCOMING_DOWNLOAD_CANCELED" => Some(Self::IncomingDownloadCanceled),
            "INCOMING_DOWNLOAD_FAILED_TOO_LARGE" => {
                Some(Self::IncomingDownloadFailedTooLarge)
            }
            "INCOMING_DOWNLOAD_FAILED_SIM_HAS_NO_DATA" => {
                Some(Self::IncomingDownloadFailedSimHasNoData)
            }
            "INCOMING_FAILED_TO_DECRYPT" => Some(Self::IncomingFailedToDecrypt),
            "INCOMING_DECRYPTION_ABORTED" => Some(Self::IncomingDecryptionAborted),
            "TOMBSTONE_PARTICIPANT_JOINED" => Some(Self::TombstoneParticipantJoined),
            "TOMBSTONE_PARTICIPANT_LEFT" => Some(Self::TombstoneParticipantLeft),
            "TOMBSTONE_SELF_LEFT" => Some(Self::TombstoneSelfLeft),
            "TOMBSTONE_RCS_GROUP_CREATED" => Some(Self::TombstoneRcsGroupCreated),
            "TOMBSTONE_MMS_GROUP_CREATED" => Some(Self::TombstoneMmsGroupCreated),
            "TOMBSTONE_SMS_BROADCAST_CREATED" => Some(Self::TombstoneSmsBroadcastCreated),
            "TOMBSTONE_ONE_ON_ONE_SMS_CREATED" => Some(Self::TombstoneOneOnOneSmsCreated),
            "TOMBSTONE_ONE_ON_ONE_RCS_CREATED" => Some(Self::TombstoneOneOnOneRcsCreated),
            "TOMBSTONE_SWITCH_TO_GROUP_MMS" => Some(Self::TombstoneSwitchToGroupMms),
            "TOMBSTONE_SWITCH_TO_BROADCAST_SMS" => {
                Some(Self::TombstoneSwitchToBroadcastSms)
            }
            "TOMBSTONE_SHOW_LINK_PREVIEWS" => Some(Self::TombstoneShowLinkPreviews),
            "TOMBSTONE_GROUP_RENAMED_LOCAL" => Some(Self::TombstoneGroupRenamedLocal),
            "TOMBSTONE_VERIFIED_SMS_APPLICABLE" => {
                Some(Self::TombstoneVerifiedSmsApplicable)
            }
            "TOMBSTONE_ENCRYPTED_ONE_ON_ONE_RCS_CREATED" => {
                Some(Self::TombstoneEncryptedOneOnOneRcsCreated)
            }
            "TOMBSTONE_PROTOCOL_SWITCH_TO_TEXT" => {
                Some(Self::TombstoneProtocolSwitchToText)
            }
            "TOMBSTONE_PROTOCOL_SWITCH_TO_RCS" => {
                Some(Self::TombstoneProtocolSwitchToRcs)
            }
            "TOMBSTONE_PROTOCOL_SWITCH_TO_ENCRYPTED_RCS" => {
                Some(Self::TombstoneProtocolSwitchToEncryptedRcs)
            }
            "TOMBSTONE_GROUP_RENAMED_GLOBAL" => Some(Self::TombstoneGroupRenamedGlobal),
            "TOMBSTONE_GROUP_NAME_CLEARED_GLOBAL" => {
                Some(Self::TombstoneGroupNameClearedGlobal)
            }
            "TOMBSTONE_PROTOCOL_SWITCH_TO_ENCRYPTED_RCS_INFO" => {
                Some(Self::TombstoneProtocolSwitchToEncryptedRcsInfo)
            }
            "TOMBSTONE_SELF_REMOVED_FROM_GROUP" => {
                Some(Self::TombstoneSelfRemovedFromGroup)
            }
            "MESSAGE_STATUS_TOMBSTONE_PARTICIPANT_REMOVED_FROM_GROUP" => {
                Some(Self::MessageStatusTombstoneParticipantRemovedFromGroup)
            }
            "MESSAGE_STATUS_TOMBSTONE_SMS_NORM_PARTICIPANT_UPGRADED" => {
                Some(Self::MessageStatusTombstoneSmsNormParticipantUpgraded)
            }
            "MESSAGE_STATUS_TOMBSTONE_RCS_NORM_PARTICIPANT_UPGRADED" => {
                Some(Self::MessageStatusTombstoneRcsNormParticipantUpgraded)
            }
            "MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_RCS_NORM_PARTICIPANT_UPGRADED" => {
                Some(Self::MessageStatusTombstoneEncryptedRcsNormParticipantUpgraded)
            }
            "MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_PARTICIPANT_JOINED" => {
                Some(Self::MessageStatusTombstoneEncryptedGroupParticipantJoined)
            }
            "MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_PARTICIPANT_JOINED_INFO" => {
                Some(Self::MessageStatusTombstoneEncryptedGroupParticipantJoinedInfo)
            }
            "MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_PARTICIPANT_LEFT" => {
                Some(Self::MessageStatusTombstoneEncryptedGroupParticipantLeft)
            }
            "MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_SELF_LEFT" => {
                Some(Self::MessageStatusTombstoneEncryptedGroupSelfLeft)
            }
            "MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_CREATED" => {
                Some(Self::MessageStatusTombstoneEncryptedGroupCreated)
            }
            "MESSAGE_STATUS_TOMBSTONE_SELF_REMOVED_FROM_ENCRYPTED_GROUP" => {
                Some(Self::MessageStatusTombstoneSelfRemovedFromEncryptedGroup)
            }
            "MESSAGE_STATUS_TOMBSTONE_PARTICIPANT_REMOVED_FROM_ENCRYPTED_GROUP" => {
                Some(Self::MessageStatusTombstoneParticipantRemovedFromEncryptedGroup)
            }
            "MESSAGE_STATUS_TOMBSTONE_SUGGESTION_SHORTCUT_STAR_TOOLSTONE" => {
                Some(Self::MessageStatusTombstoneSuggestionShortcutStarToolstone)
            }
            "MESSAGE_STATUS_TOMBSTONE_GROUP_PROTOCOL_SWITCH_RCS_TO_E2EE" => {
                Some(Self::MessageStatusTombstoneGroupProtocolSwitchRcsToE2ee)
            }
            "MESSAGE_STATUS_TOMBSTONE_GROUP_PROTOCOL_SWITCH_E2EE_TO_RCS" => {
                Some(Self::MessageStatusTombstoneGroupProtocolSwitchE2eeToRcs)
            }
            "MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_TEXT_TO_E2EE" => {
                Some(Self::MessageStatusTombstoneProtocolSwitchTextToE2ee)
            }
            "MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_E2EE_TO_TEXT" => {
                Some(Self::MessageStatusTombstoneProtocolSwitchE2eeToText)
            }
            "MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_RCS_TO_E2EE" => {
                Some(Self::MessageStatusTombstoneProtocolSwitchRcsToE2ee)
            }
            "MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_E2EE_TO_RCS" => {
                Some(Self::MessageStatusTombstoneProtocolSwitchE2eeToRcs)
            }
            "MESSAGE_STATUS_TOMBSTONE_SATELLITE_EDUCATION" => {
                Some(Self::MessageStatusTombstoneSatelliteEducation)
            }
            "MESSAGE_STATUS_TOMBSTONE_RBM_SIM_SWITCH" => {
                Some(Self::MessageStatusTombstoneRbmSimSwitch)
            }
            "MESSAGE_STATUS_TOMBSTONE_RBM_PRIVACY_NOTICE" => {
                Some(Self::MessageStatusTombstoneRbmPrivacyNotice)
            }
            "MESSAGE_STATUS_TOMBSTONE_PENPAL_CONVERSATION_NOTICE" => {
                Some(Self::MessageStatusTombstonePenpalConversationNotice)
            }
            "MESSAGE_STATUS_TOMBSTONE_MEET_OTHER_PARTICIPANT_REACHABLE" => {
                Some(Self::MessageStatusTombstoneMeetOtherParticipantReachable)
            }
            "MESSAGE_STATUS_TOMBSTONE_MISSED_VIDEO_CALL" => {
                Some(Self::MessageStatusTombstoneMissedVideoCall)
            }
            "MESSAGE_STATUS_TOMBSTONE_PARTICIPANT_THEME_CHANGE" => {
                Some(Self::MessageStatusTombstoneParticipantThemeChange)
            }
            "MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_SUCCESS_HELP_STILL_NEEDED" => {
                Some(
                    Self::MessageStatusTombstoneSatelliteEndOfEmergencySuccessHelpStillNeeded,
                )
            }
            "MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_SUCCESS_HELP_NO_LONGER_NEEDED" => {
                Some(
                    Self::MessageStatusTombstoneSatelliteEndOfEmergencySuccessHelpNoLongerNeeded,
                )
            }
            "MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_FAILURE_HELP_STILL_NEEDED" => {
                Some(
                    Self::MessageStatusTombstoneSatelliteEndOfEmergencyFailureHelpStillNeeded,
                )
            }
            "MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_FAILURE_HELP_NO_LONGER_NEEDED" => {
                Some(
                    Self::MessageStatusTombstoneSatelliteEndOfEmergencyFailureHelpNoLongerNeeded,
                )
            }
            "MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_UNEXPECTED_END" => {
                Some(Self::MessageStatusTombstoneSatelliteEndOfEmergencyUnexpectedEnd)
            }
            "MESSAGE_STATUS_TOMBSTONE_SATELLITE_MESSAGING_TOOLSTONE" => {
                Some(Self::MessageStatusTombstoneSatelliteMessagingToolstone)
            }
            "MESSAGE_STATUS_TOMBSTONE_GROUP_PROTOCOL_SWITCH_E2EE_TO_MMS" => {
                Some(Self::MessageStatusTombstoneGroupProtocolSwitchE2eeToMms)
            }
            "MESSAGE_STATUS_TOMBSTONE_PENPAL_PROACTIVE_MESSAGE_NOTICE" => {
                Some(Self::MessageStatusTombstonePenpalProactiveMessageNotice)
            }
            "MESSAGE_STATUS_TOMBSTONE_SUGGESTION_POSSIBLE_SCAM_TOOLSTONE" => {
                Some(Self::MessageStatusTombstoneSuggestionPossibleScamToolstone)
            }
            "MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_SENT" => {
                Some(Self::MessageStatusTombstoneChatbotUnsubscribeSent)
            }
            "MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_SENT" => {
                Some(Self::MessageStatusTombstoneChatbotSubscribeSent)
            }
            "MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_CONFIRMED" => {
                Some(Self::MessageStatusTombstoneChatbotUnsubscribeConfirmed)
            }
            "MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_CONFIRMED" => {
                Some(Self::MessageStatusTombstoneChatbotSubscribeConfirmed)
            }
            "MESSAGE_STATUS_TOMBSTONE_ACTIVE_SELF_IDENTITY_CHANGED" => {
                Some(Self::MessageStatusTombstoneActiveSelfIdentityChanged)
            }
            "MESSAGE_STATUS_TOMBSTONE_GROUP_ICON_CHANGED_GLOBAL" => {
                Some(Self::MessageStatusTombstoneGroupIconChangedGlobal)
            }
            "MESSAGE_STATUS_TOMBSTONE_GROUP_ICON_CLEARED_GLOBAL" => {
                Some(Self::MessageStatusTombstoneGroupIconClearedGlobal)
            }
            "MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_ERROR" => {
                Some(Self::MessageStatusTombstoneChatbotUnsubscribeError)
            }
            "MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_ERROR" => {
                Some(Self::MessageStatusTombstoneChatbotSubscribeError)
            }
            "MESSAGE_STATUS_TOMBSTONE_EMERGENCY_CONVERSATION_CREATED" => {
                Some(Self::MessageStatusTombstoneEmergencyConversationCreated)
            }
            "MESSAGE_STATUS_TOMBSTONE_SENSITIVE_CONTENT_WARNING_TOOLSTONE" => {
                Some(Self::MessageStatusTombstoneSensitiveContentWarningToolstone)
            }
            "MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_CONFIRMED_NO_LINK" => {
                Some(Self::MessageStatusTombstoneChatbotUnsubscribeConfirmedNoLink)
            }
            "MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_CONFIRMED_NO_LINK" => {
                Some(Self::MessageStatusTombstoneChatbotSubscribeConfirmedNoLink)
            }
            "MESSAGE_STATUS_TOMBSTONE_EMERGENCY_QUESTIONNAIRE" => {
                Some(Self::MessageStatusTombstoneEmergencyQuestionnaire)
            }
            "MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_SENT_NO_LINK" => {
                Some(Self::MessageStatusTombstoneChatbotUnsubscribeSentNoLink)
            }
            "MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_SENT_NO_LINK" => {
                Some(Self::MessageStatusTombstoneChatbotSubscribeSentNoLink)
            }
            "MESSAGE_STATUS_TOMBSTONE_RCS_GROUP_JOINED_BY_LINK" => {
                Some(Self::MessageStatusTombstoneRcsGroupJoinedByLink)
            }
            "MESSAGE_STATUS_TOMBSTONE_INVITE_LINK_ENABLED" => {
                Some(Self::MessageStatusTombstoneInviteLinkEnabled)
            }
            "MESSAGE_STATUS_TOMBSTONE_INVITE_LINK_DISABLED" => {
                Some(Self::MessageStatusTombstoneInviteLinkDisabled)
            }
            "MESSAGE_STATUS_TOMBSTONE_INVITE_LINK_RESET_MANUALLY" => {
                Some(Self::MessageStatusTombstoneInviteLinkResetManually)
            }
            "MESSAGE_STATUS_TOMBSTONE_INVITE_LINK_RESET_AUTOMATICALLY" => {
                Some(Self::MessageStatusTombstoneInviteLinkResetAutomatically)
            }
            "MESSAGE_DELETED" => Some(Self::MessageDeleted),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ConversationStatus {
    UnknownConversationStatus = 0,
    Active = 1,
    Archived = 2,
    Deleted = 3,
    KeepArchived = 4,
    SpamFolder = 5,
    BlockedFolder = 6,
    CrossCountryFolder = 7,
}
impl ConversationStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UnknownConversationStatus => "UNKNOWN_CONVERSATION_STATUS",
            Self::Active => "ACTIVE",
            Self::Archived => "ARCHIVED",
            Self::Deleted => "DELETED",
            Self::KeepArchived => "KEEP_ARCHIVED",
            Self::SpamFolder => "SPAM_FOLDER",
            Self::BlockedFolder => "BLOCKED_FOLDER",
            Self::CrossCountryFolder => "CROSS_COUNTRY_FOLDER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_CONVERSATION_STATUS" => Some(Self::UnknownConversationStatus),
            "ACTIVE" => Some(Self::Active),
            "ARCHIVED" => Some(Self::Archived),
            "DELETED" => Some(Self::Deleted),
            "KEEP_ARCHIVED" => Some(Self::KeepArchived),
            "SPAM_FOLDER" => Some(Self::SpamFolder),
            "BLOCKED_FOLDER" => Some(Self::BlockedFolder),
            "CROSS_COUNTRY_FOLDER" => Some(Self::CrossCountryFolder),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MediaFormats {
    UnspecifiedType = 0,
    ImageJpeg = 1,
    ImageJpg = 2,
    ImagePng = 3,
    ImageGif = 4,
    ImageWbmp = 5,
    ImageXMsBmp = 6,
    ImageUnspecified = 7,
    VideoMp4 = 8,
    Video3g2 = 9,
    Video3gpp = 10,
    VideoWebm = 11,
    VideoMkv = 12,
    VideoUnspecified = 13,
    AudioAac = 14,
    AudioAmr = 15,
    AudioMp3 = 16,
    AudioMpeg = 17,
    AudioMpg = 18,
    AudioMp4 = 19,
    AudioMp4Latm = 20,
    Audio3gpp = 21,
    AudioOgg = 22,
    AudioUnspecified = 23,
    TextVcard = 24,
    AppPdf = 25,
    AppTxt = 26,
    AppHtml = 27,
    AppDoc = 28,
    AppDocx = 29,
    AppPptx = 30,
    AppPpt = 31,
    AppXlsx = 32,
    AppXls = 33,
    AppApk = 34,
    AppZip = 35,
    AppJar = 36,
    AppUnspecified = 37,
    CalTextVcalendar = 38,
    CalTextXvcalendar = 39,
    CalTextCalendar = 40,
    CalApplicationVcs = 41,
    CalApplicationIcs = 42,
    CalApplicationHbsvcs = 43,
}
impl MediaFormats {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UnspecifiedType => "UNSPECIFIED_TYPE",
            Self::ImageJpeg => "IMAGE_JPEG",
            Self::ImageJpg => "IMAGE_JPG",
            Self::ImagePng => "IMAGE_PNG",
            Self::ImageGif => "IMAGE_GIF",
            Self::ImageWbmp => "IMAGE_WBMP",
            Self::ImageXMsBmp => "IMAGE_X_MS_BMP",
            Self::ImageUnspecified => "IMAGE_UNSPECIFIED",
            Self::VideoMp4 => "VIDEO_MP4",
            Self::Video3g2 => "VIDEO_3G2",
            Self::Video3gpp => "VIDEO_3GPP",
            Self::VideoWebm => "VIDEO_WEBM",
            Self::VideoMkv => "VIDEO_MKV",
            Self::VideoUnspecified => "VIDEO_UNSPECIFIED",
            Self::AudioAac => "AUDIO_AAC",
            Self::AudioAmr => "AUDIO_AMR",
            Self::AudioMp3 => "AUDIO_MP3",
            Self::AudioMpeg => "AUDIO_MPEG",
            Self::AudioMpg => "AUDIO_MPG",
            Self::AudioMp4 => "AUDIO_MP4",
            Self::AudioMp4Latm => "AUDIO_MP4_LATM",
            Self::Audio3gpp => "AUDIO_3GPP",
            Self::AudioOgg => "AUDIO_OGG",
            Self::AudioUnspecified => "AUDIO_UNSPECIFIED",
            Self::TextVcard => "TEXT_VCARD",
            Self::AppPdf => "APP_PDF",
            Self::AppTxt => "APP_TXT",
            Self::AppHtml => "APP_HTML",
            Self::AppDoc => "APP_DOC",
            Self::AppDocx => "APP_DOCX",
            Self::AppPptx => "APP_PPTX",
            Self::AppPpt => "APP_PPT",
            Self::AppXlsx => "APP_XLSX",
            Self::AppXls => "APP_XLS",
            Self::AppApk => "APP_APK",
            Self::AppZip => "APP_ZIP",
            Self::AppJar => "APP_JAR",
            Self::AppUnspecified => "APP_UNSPECIFIED",
            Self::CalTextVcalendar => "CAL_TEXT_VCALENDAR",
            Self::CalTextXvcalendar => "CAL_TEXT_XVCALENDAR",
            Self::CalTextCalendar => "CAL_TEXT_CALENDAR",
            Self::CalApplicationVcs => "CAL_APPLICATION_VCS",
            Self::CalApplicationIcs => "CAL_APPLICATION_ICS",
            Self::CalApplicationHbsvcs => "CAL_APPLICATION_HBSVCS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNSPECIFIED_TYPE" => Some(Self::UnspecifiedType),
            "IMAGE_JPEG" => Some(Self::ImageJpeg),
            "IMAGE_JPG" => Some(Self::ImageJpg),
            "IMAGE_PNG" => Some(Self::ImagePng),
            "IMAGE_GIF" => Some(Self::ImageGif),
            "IMAGE_WBMP" => Some(Self::ImageWbmp),
            "IMAGE_X_MS_BMP" => Some(Self::ImageXMsBmp),
            "IMAGE_UNSPECIFIED" => Some(Self::ImageUnspecified),
            "VIDEO_MP4" => Some(Self::VideoMp4),
            "VIDEO_3G2" => Some(Self::Video3g2),
            "VIDEO_3GPP" => Some(Self::Video3gpp),
            "VIDEO_WEBM" => Some(Self::VideoWebm),
            "VIDEO_MKV" => Some(Self::VideoMkv),
            "VIDEO_UNSPECIFIED" => Some(Self::VideoUnspecified),
            "AUDIO_AAC" => Some(Self::AudioAac),
            "AUDIO_AMR" => Some(Self::AudioAmr),
            "AUDIO_MP3" => Some(Self::AudioMp3),
            "AUDIO_MPEG" => Some(Self::AudioMpeg),
            "AUDIO_MPG" => Some(Self::AudioMpg),
            "AUDIO_MP4" => Some(Self::AudioMp4),
            "AUDIO_MP4_LATM" => Some(Self::AudioMp4Latm),
            "AUDIO_3GPP" => Some(Self::Audio3gpp),
            "AUDIO_OGG" => Some(Self::AudioOgg),
            "AUDIO_UNSPECIFIED" => Some(Self::AudioUnspecified),
            "TEXT_VCARD" => Some(Self::TextVcard),
            "APP_PDF" => Some(Self::AppPdf),
            "APP_TXT" => Some(Self::AppTxt),
            "APP_HTML" => Some(Self::AppHtml),
            "APP_DOC" => Some(Self::AppDoc),
            "APP_DOCX" => Some(Self::AppDocx),
            "APP_PPTX" => Some(Self::AppPptx),
            "APP_PPT" => Some(Self::AppPpt),
            "APP_XLSX" => Some(Self::AppXlsx),
            "APP_XLS" => Some(Self::AppXls),
            "APP_APK" => Some(Self::AppApk),
            "APP_ZIP" => Some(Self::AppZip),
            "APP_JAR" => Some(Self::AppJar),
            "APP_UNSPECIFIED" => Some(Self::AppUnspecified),
            "CAL_TEXT_VCALENDAR" => Some(Self::CalTextVcalendar),
            "CAL_TEXT_XVCALENDAR" => Some(Self::CalTextXvcalendar),
            "CAL_TEXT_CALENDAR" => Some(Self::CalTextCalendar),
            "CAL_APPLICATION_VCS" => Some(Self::CalApplicationVcs),
            "CAL_APPLICATION_ICS" => Some(Self::CalApplicationIcs),
            "CAL_APPLICATION_HBSVCS" => Some(Self::CalApplicationHbsvcs),
            _ => None,
        }
    }
}
