// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "events.UpdateEvents")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateEvents {
    #[prost(oneof = "update_events::Event", tags = "2, 3, 4, 5, 6, 7, 15")]
    pub event: ::core::option::Option<update_events::Event>,
}
/// Nested message and enum types in `UpdateEvents`.
pub mod update_events {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "2")]
        ConversationEvent(super::ConversationEvent),
        #[prost(message, tag = "3")]
        MessageEvent(super::MessageEvent),
        #[prost(message, tag = "4")]
        TypingEvent(super::TypingEvent),
        #[prost(message, tag = "5")]
        SettingsEvent(super::super::settings::Settings),
        #[prost(message, tag = "6")]
        UserAlertEvent(super::UserAlertEvent),
        #[prost(message, tag = "7")]
        BrowserPresenceCheckEvent(super::BrowserPresenceCheckEvent),
        /// ParticipantsEvent participantsEvent = 8;
        /// ConversationTypeEvent conversationTypeEvent = 9;
        /// FavoriteStickersEvent favoriteStickersEvent = 10;
        /// RecentStickerEvent recentStickerEvent = 11;
        /// CloudStoreInfoEvent cloudStoreInfoEvent = 12;
        /// BlobForAttachmentProgressUpdate blobForAttachmentProgressUpdate = 13;
        #[prost(message, tag = "15")]
        AccountChange(super::AccountChangeOrSomethingEvent),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "events.EncryptedData2Container")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EncryptedData2Container {
    #[prost(message, optional, tag = "2")]
    pub account_change: ::core::option::Option<AccountChangeOrSomethingEvent>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "events.AccountChangeOrSomethingEvent")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AccountChangeOrSomethingEvent {
    #[prost(string, tag = "1")]
    pub account: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub enabled: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "events.ConversationEvent")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConversationEvent {
    #[prost(message, repeated, tag = "2")]
    pub data: ::prost::alloc::vec::Vec<super::conversations::Conversation>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "events.TypingEvent")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TypingEvent {
    #[prost(message, optional, tag = "2")]
    pub data: ::core::option::Option<TypingData>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "events.MessageEvent")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageEvent {
    #[prost(message, repeated, tag = "2")]
    pub data: ::prost::alloc::vec::Vec<super::conversations::Message>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "events.UserAlertEvent")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserAlertEvent {
    #[prost(enumeration = "AlertType", tag = "2")]
    pub alert_type: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "events.BrowserPresenceCheckEvent")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BrowserPresenceCheckEvent {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "events.TypingData")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TypingData {
    #[prost(string, tag = "1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub user: ::core::option::Option<User>,
    #[prost(enumeration = "TypingTypes", tag = "3")]
    pub r#type: i32,
    #[prost(message, optional, tag = "4")]
    pub some_kind_of_group_id: ::core::option::Option<
        super::conversations::SomeKindOfGroupId,
    >,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "events.MoreTypingData")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MoreTypingData {
    #[prost(string, tag = "1")]
    pub conversation_id: ::prost::alloc::string::String,
    /// Field 2 has some weird hash or something in groups?
    #[prost(string, repeated, tag = "3")]
    pub number: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "events.User")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct User {
    #[prost(int64, tag = "1")]
    pub field1: i64,
    #[prost(string, tag = "2")]
    pub number: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "events.RPCPairData")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RpcPairData {
    #[prost(oneof = "rpc_pair_data::Event", tags = "4, 5")]
    pub event: ::core::option::Option<rpc_pair_data::Event>,
}
/// Nested message and enum types in `RPCPairData`.
pub mod rpc_pair_data {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "4")]
        Paired(super::super::authentication::PairedData),
        #[prost(message, tag = "5")]
        Revoked(super::super::authentication::RevokePairData),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AlertType {
    Unknown = 0,
    /// Emitted whenever browser connection becomes inactive
    BrowserInactive = 1,
    /// Emitted whenever a new browser session is created
    BrowserActive = 2,
    /// Emitted when the paired device connects to data
    MobileDataConnection = 3,
    /// Emitted when the paired device connects to wifi
    MobileWifiConnection = 4,
    /// Emitted if the paired device reaches low battery
    MobileBatteryLow = 5,
    /// Emitted if the paired device has restored battery enough to not be considered low
    MobileBatteryRestored = 6,
    /// Emitted whenever browser connection becomes inactive due to timeout
    BrowserInactiveFromTimeout = 7,
    /// Emitted whenever browser connection becomes inactive due to inactivity
    BrowserInactiveFromInactivity = 8,
    /// Emitted whenever RCS connection has been established successfully
    RcsConnection = 9,
    /// Unknown
    ObserverRegistered = 10,
    /// Emitted whenever the paired device is attempting to sync db
    MobileDatabaseSyncing = 11,
    /// Emitted whenever the paired device has completed the db sync
    MobileDatabaseSyncComplete = 12,
    /// Emitted whenever the paired device has begun syncing the db
    MobileDatabaseSyncStarted = 13,
    /// Emitted whenever the paired device has successfully synced a chunk of the db
    MobileDatabasePartialSyncCompleted = 14,
    /// Emitted whenever the paired device has begun syncing a chunk of the db
    MobileDatabasePartialSyncStarted = 15,
    /// Emitted whenever the paired device has begun refreshing contacts
    ContactsRefreshStarted = 16,
    /// Emitted whenever the paired device has successfully refreshed contacts
    ContactsRefreshCompleted = 17,
    DisconnectedFromSatellite = 18,
    BrMessageRestoring = 19,
    BrMessageRestoreCompleted = 20,
    BrMessageRestoreStarted = 21,
    PushThrottling = 22,
    PushThrottleStarted = 23,
    PushThrottleEnded = 24,
    PushThrottleStartedInDarkLaunch = 25,
    PushThrottleEndedInDarkLaunch = 26,
    PushThrottlingInDarkLaunch = 27,
}
impl AlertType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "ALERT_TYPE_UNKNOWN",
            Self::BrowserInactive => "BROWSER_INACTIVE",
            Self::BrowserActive => "BROWSER_ACTIVE",
            Self::MobileDataConnection => "MOBILE_DATA_CONNECTION",
            Self::MobileWifiConnection => "MOBILE_WIFI_CONNECTION",
            Self::MobileBatteryLow => "MOBILE_BATTERY_LOW",
            Self::MobileBatteryRestored => "MOBILE_BATTERY_RESTORED",
            Self::BrowserInactiveFromTimeout => "BROWSER_INACTIVE_FROM_TIMEOUT",
            Self::BrowserInactiveFromInactivity => "BROWSER_INACTIVE_FROM_INACTIVITY",
            Self::RcsConnection => "RCS_CONNECTION",
            Self::ObserverRegistered => "OBSERVER_REGISTERED",
            Self::MobileDatabaseSyncing => "MOBILE_DATABASE_SYNCING",
            Self::MobileDatabaseSyncComplete => "MOBILE_DATABASE_SYNC_COMPLETE",
            Self::MobileDatabaseSyncStarted => "MOBILE_DATABASE_SYNC_STARTED",
            Self::MobileDatabasePartialSyncCompleted => {
                "MOBILE_DATABASE_PARTIAL_SYNC_COMPLETED"
            }
            Self::MobileDatabasePartialSyncStarted => {
                "MOBILE_DATABASE_PARTIAL_SYNC_STARTED"
            }
            Self::ContactsRefreshStarted => "CONTACTS_REFRESH_STARTED",
            Self::ContactsRefreshCompleted => "CONTACTS_REFRESH_COMPLETED",
            Self::DisconnectedFromSatellite => "DISCONNECTED_FROM_SATELLITE",
            Self::BrMessageRestoring => "BR_MESSAGE_RESTORING",
            Self::BrMessageRestoreCompleted => "BR_MESSAGE_RESTORE_COMPLETED",
            Self::BrMessageRestoreStarted => "BR_MESSAGE_RESTORE_STARTED",
            Self::PushThrottling => "PUSH_THROTTLING",
            Self::PushThrottleStarted => "PUSH_THROTTLE_STARTED",
            Self::PushThrottleEnded => "PUSH_THROTTLE_ENDED",
            Self::PushThrottleStartedInDarkLaunch => {
                "PUSH_THROTTLE_STARTED_IN_DARK_LAUNCH"
            }
            Self::PushThrottleEndedInDarkLaunch => "PUSH_THROTTLE_ENDED_IN_DARK_LAUNCH",
            Self::PushThrottlingInDarkLaunch => "PUSH_THROTTLING_IN_DARK_LAUNCH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ALERT_TYPE_UNKNOWN" => Some(Self::Unknown),
            "BROWSER_INACTIVE" => Some(Self::BrowserInactive),
            "BROWSER_ACTIVE" => Some(Self::BrowserActive),
            "MOBILE_DATA_CONNECTION" => Some(Self::MobileDataConnection),
            "MOBILE_WIFI_CONNECTION" => Some(Self::MobileWifiConnection),
            "MOBILE_BATTERY_LOW" => Some(Self::MobileBatteryLow),
            "MOBILE_BATTERY_RESTORED" => Some(Self::MobileBatteryRestored),
            "BROWSER_INACTIVE_FROM_TIMEOUT" => Some(Self::BrowserInactiveFromTimeout),
            "BROWSER_INACTIVE_FROM_INACTIVITY" => {
                Some(Self::BrowserInactiveFromInactivity)
            }
            "RCS_CONNECTION" => Some(Self::RcsConnection),
            "OBSERVER_REGISTERED" => Some(Self::ObserverRegistered),
            "MOBILE_DATABASE_SYNCING" => Some(Self::MobileDatabaseSyncing),
            "MOBILE_DATABASE_SYNC_COMPLETE" => Some(Self::MobileDatabaseSyncComplete),
            "MOBILE_DATABASE_SYNC_STARTED" => Some(Self::MobileDatabaseSyncStarted),
            "MOBILE_DATABASE_PARTIAL_SYNC_COMPLETED" => {
                Some(Self::MobileDatabasePartialSyncCompleted)
            }
            "MOBILE_DATABASE_PARTIAL_SYNC_STARTED" => {
                Some(Self::MobileDatabasePartialSyncStarted)
            }
            "CONTACTS_REFRESH_STARTED" => Some(Self::ContactsRefreshStarted),
            "CONTACTS_REFRESH_COMPLETED" => Some(Self::ContactsRefreshCompleted),
            "DISCONNECTED_FROM_SATELLITE" => Some(Self::DisconnectedFromSatellite),
            "BR_MESSAGE_RESTORING" => Some(Self::BrMessageRestoring),
            "BR_MESSAGE_RESTORE_COMPLETED" => Some(Self::BrMessageRestoreCompleted),
            "BR_MESSAGE_RESTORE_STARTED" => Some(Self::BrMessageRestoreStarted),
            "PUSH_THROTTLING" => Some(Self::PushThrottling),
            "PUSH_THROTTLE_STARTED" => Some(Self::PushThrottleStarted),
            "PUSH_THROTTLE_ENDED" => Some(Self::PushThrottleEnded),
            "PUSH_THROTTLE_STARTED_IN_DARK_LAUNCH" => {
                Some(Self::PushThrottleStartedInDarkLaunch)
            }
            "PUSH_THROTTLE_ENDED_IN_DARK_LAUNCH" => {
                Some(Self::PushThrottleEndedInDarkLaunch)
            }
            "PUSH_THROTTLING_IN_DARK_LAUNCH" => Some(Self::PushThrottlingInDarkLaunch),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TypingTypes {
    StoppedTyping = 0,
    StartedTyping = 1,
}
impl TypingTypes {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::StoppedTyping => "STOPPED_TYPING",
            Self::StartedTyping => "STARTED_TYPING",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STOPPED_TYPING" => Some(Self::StoppedTyping),
            "STARTED_TYPING" => Some(Self::StartedTyping),
            _ => None,
        }
    }
}
