// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "rpc.StartAckMessage")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartAckMessage {
    #[prost(int32, optional, tag = "1")]
    pub count: ::core::option::Option<i32>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "rpc.LongPollingPayload")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LongPollingPayload {
    #[prost(message, optional, tag = "2")]
    pub data: ::core::option::Option<IncomingRpcMessage>,
    #[prost(message, optional, tag = "3")]
    pub heartbeat: ::core::option::Option<super::util::EmptyArr>,
    #[prost(message, optional, tag = "4")]
    pub ack: ::core::option::Option<StartAckMessage>,
    #[prost(message, optional, tag = "5")]
    pub start_read: ::core::option::Option<super::util::EmptyArr>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "rpc.IncomingRPCMessage")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IncomingRpcMessage {
    #[prost(string, tag = "1")]
    pub response_id: ::prost::alloc::string::String,
    #[prost(enumeration = "BugleRoute", tag = "2")]
    pub bugle_route: i32,
    #[prost(uint64, tag = "3")]
    pub start_execute: u64,
    #[prost(enumeration = "MessageType", tag = "5")]
    pub message_type: i32,
    #[prost(uint64, tag = "6")]
    pub finish_execute: u64,
    #[prost(uint64, tag = "7")]
    pub microseconds_taken: u64,
    #[prost(message, optional, tag = "8")]
    pub mobile: ::core::option::Option<super::authentication::Device>,
    #[prost(message, optional, tag = "9")]
    pub browser: ::core::option::Option<super::authentication::Device>,
    /// Either a RPCMessageData or a RPCPairData encoded as bytes
    #[prost(bytes = "vec", tag = "12")]
    pub message_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "17")]
    pub signature_id: ::prost::alloc::string::String,
    #[prost(string, tag = "21")]
    pub timestamp: ::prost::alloc::string::String,
    /// Completely unsure about this, but it seems to be present for weird intermediate responses
    #[prost(message, optional, tag = "23")]
    pub gditto_source: ::core::option::Option<incoming_rpc_message::GDittoSource>,
}
/// Nested message and enum types in `IncomingRPCMessage`.
pub mod incoming_rpc_message {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(message_name = "rpc.IncomingRPCMessage.GDittoSource")]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct GDittoSource {
        #[prost(int32, tag = "2")]
        pub device_id: i32,
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "rpc.RPCMessageData")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RpcMessageData {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub timestamp: i64,
    #[prost(enumeration = "ActionType", tag = "4")]
    pub action: i32,
    #[prost(bytes = "vec", tag = "5")]
    pub unencrypted_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "6")]
    pub bool1: bool,
    #[prost(bool, tag = "7")]
    pub bool2: bool,
    #[prost(bytes = "vec", tag = "8")]
    pub encrypted_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "9")]
    pub bool3: bool,
    #[prost(bytes = "vec", tag = "11")]
    pub encrypted_data2: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "rpc.OutgoingRPCMessage")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OutgoingRpcMessage {
    #[prost(message, optional, tag = "1")]
    pub mobile: ::core::option::Option<super::authentication::Device>,
    #[prost(message, optional, tag = "2")]
    pub data: ::core::option::Option<outgoing_rpc_message::Data>,
    #[prost(message, optional, tag = "3")]
    pub auth: ::core::option::Option<outgoing_rpc_message::Auth>,
    #[prost(int64, tag = "5")]
    pub ttl: i64,
    #[prost(string, repeated, tag = "9")]
    pub dest_registration_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Nested message and enum types in `OutgoingRPCMessage`.
pub mod outgoing_rpc_message {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(message_name = "rpc.OutgoingRPCMessage.Auth")]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Auth {
        #[prost(string, tag = "1")]
        pub request_id: ::prost::alloc::string::String,
        #[prost(bytes = "vec", tag = "6")]
        pub tachyon_auth_token: ::prost::alloc::vec::Vec<u8>,
        #[prost(message, optional, tag = "7")]
        pub config_version: ::core::option::Option<
            super::super::authentication::ConfigVersion,
        >,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(message_name = "rpc.OutgoingRPCMessage.Data")]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Data {
        #[prost(string, tag = "1")]
        pub request_id: ::prost::alloc::string::String,
        #[prost(enumeration = "super::BugleRoute", tag = "2")]
        pub bugle_route: i32,
        /// OutgoingRPCData encoded as bytes
        #[prost(bytes = "vec", tag = "12")]
        pub message_data: ::prost::alloc::vec::Vec<u8>,
        #[prost(message, optional, tag = "23")]
        pub message_type_data: ::core::option::Option<data::Type>,
    }
    /// Nested message and enum types in `Data`.
    pub mod data {
        #[derive(serde::Serialize, serde::Deserialize)]
        #[derive(::prost_reflect::ReflectMessage)]
        #[prost_reflect(message_name = "rpc.OutgoingRPCMessage.Data.Type")]
        #[prost_reflect(
            file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
        )]
        #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct Type {
            #[prost(message, optional, tag = "1")]
            pub empty_arr: ::core::option::Option<super::super::super::util::EmptyArr>,
            #[prost(enumeration = "super::super::MessageType", tag = "2")]
            pub message_type: i32,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "rpc.OutgoingRPCData")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OutgoingRpcData {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(enumeration = "ActionType", tag = "2")]
    pub action: i32,
    #[prost(bytes = "vec", tag = "3")]
    pub unencrypted_proto_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub encrypted_proto_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "6")]
    pub session_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "rpc.OutgoingRPCResponse")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OutgoingRpcResponse {
    #[prost(message, optional, tag = "1")]
    pub some_identifier: ::core::option::Option<outgoing_rpc_response::SomeIdentifier>,
    /// This is not present for AckMessage responses, only for SendMessage
    #[prost(string, optional, tag = "2")]
    pub timestamp: ::core::option::Option<::prost::alloc::string::String>,
}
/// Nested message and enum types in `OutgoingRPCResponse`.
pub mod outgoing_rpc_response {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(message_name = "rpc.OutgoingRPCResponse.SomeIdentifier")]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct SomeIdentifier {
        /// 1 -> unknown
        #[prost(string, tag = "2")]
        pub some_number: ::prost::alloc::string::String,
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BugleRoute {
    Unknown = 0,
    DataEvent = 19,
    PairEvent = 14,
    GaiaEvent = 7,
}
impl BugleRoute {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "Unknown",
            Self::DataEvent => "DataEvent",
            Self::PairEvent => "PairEvent",
            Self::GaiaEvent => "GaiaEvent",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Unknown" => Some(Self::Unknown),
            "DataEvent" => Some(Self::DataEvent),
            "PairEvent" => Some(Self::PairEvent),
            "GaiaEvent" => Some(Self::GaiaEvent),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ActionType {
    Unspecified = 0,
    ListConversations = 1,
    ListMessages = 2,
    SendMessage = 3,
    MessageUpdates = 4,
    ListContacts = 6,
    ConversationUpdates = 7,
    GetOrCreateConversation = 9,
    MessageRead = 10,
    BrowserPresenceCheck = 11,
    TypingUpdates = 12,
    SettingsUpdate = 13,
    UserAlert = 14,
    UpdateConversation = 15,
    GetUpdates = 16,
    AckBrowserPresence = 17,
    ListStickerSets = 18,
    LeaveRcsGroup = 19,
    AddParticipantToRcsGroup = 20,
    GetConversationType = 21,
    NotifyDittoActivity = 22,
    DeleteMessage = 23,
    InstallStickerSet = 24,
    ResendMessage = 25,
    GetContactRcsGroupStatus = 26,
    DownloadMessage = 27,
    ListTopContacts = 28,
    GetContactsThumbnail = 29,
    ChangeParticipantColor = 30,
    IsBugleDefault = 31,
    StickerUserContext = 32,
    FavoriteStickerPacks = 33,
    RecentStickers = 34,
    UpdateRecentStickers = 35,
    GetFullSizeImage = 36,
    GetParticipantsThumbnail = 37,
    SendReaction = 38,
    SendReply = 39,
    GetBlobForAttachment = 40,
    GetDevicesAvailableForGaiaPairing = 41,
    CreateGaiaPairing = 42,
    GetConversation = 43,
    CreateGaiaPairingClientInit = 44,
    CreateGaiaPairingClientFinished = 45,
    UnpairGaiaPairing = 46,
    CancelGaiaPairing = 47,
    Prewarm = 48,
    ConversationGroupNameSearch = 49,
    LinkRcsIdentity = 50,
    UnlinkRcsIdentity = 51,
}
impl ActionType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "UNSPECIFIED",
            Self::ListConversations => "LIST_CONVERSATIONS",
            Self::ListMessages => "LIST_MESSAGES",
            Self::SendMessage => "SEND_MESSAGE",
            Self::MessageUpdates => "MESSAGE_UPDATES",
            Self::ListContacts => "LIST_CONTACTS",
            Self::ConversationUpdates => "CONVERSATION_UPDATES",
            Self::GetOrCreateConversation => "GET_OR_CREATE_CONVERSATION",
            Self::MessageRead => "MESSAGE_READ",
            Self::BrowserPresenceCheck => "BROWSER_PRESENCE_CHECK",
            Self::TypingUpdates => "TYPING_UPDATES",
            Self::SettingsUpdate => "SETTINGS_UPDATE",
            Self::UserAlert => "USER_ALERT",
            Self::UpdateConversation => "UPDATE_CONVERSATION",
            Self::GetUpdates => "GET_UPDATES",
            Self::AckBrowserPresence => "ACK_BROWSER_PRESENCE",
            Self::ListStickerSets => "LIST_STICKER_SETS",
            Self::LeaveRcsGroup => "LEAVE_RCS_GROUP",
            Self::AddParticipantToRcsGroup => "ADD_PARTICIPANT_TO_RCS_GROUP",
            Self::GetConversationType => "GET_CONVERSATION_TYPE",
            Self::NotifyDittoActivity => "NOTIFY_DITTO_ACTIVITY",
            Self::DeleteMessage => "DELETE_MESSAGE",
            Self::InstallStickerSet => "INSTALL_STICKER_SET",
            Self::ResendMessage => "RESEND_MESSAGE",
            Self::GetContactRcsGroupStatus => "GET_CONTACT_RCS_GROUP_STATUS",
            Self::DownloadMessage => "DOWNLOAD_MESSAGE",
            Self::ListTopContacts => "LIST_TOP_CONTACTS",
            Self::GetContactsThumbnail => "GET_CONTACTS_THUMBNAIL",
            Self::ChangeParticipantColor => "CHANGE_PARTICIPANT_COLOR",
            Self::IsBugleDefault => "IS_BUGLE_DEFAULT",
            Self::StickerUserContext => "STICKER_USER_CONTEXT",
            Self::FavoriteStickerPacks => "FAVORITE_STICKER_PACKS",
            Self::RecentStickers => "RECENT_STICKERS",
            Self::UpdateRecentStickers => "UPDATE_RECENT_STICKERS",
            Self::GetFullSizeImage => "GET_FULL_SIZE_IMAGE",
            Self::GetParticipantsThumbnail => "GET_PARTICIPANTS_THUMBNAIL",
            Self::SendReaction => "SEND_REACTION",
            Self::SendReply => "SEND_REPLY",
            Self::GetBlobForAttachment => "GET_BLOB_FOR_ATTACHMENT",
            Self::GetDevicesAvailableForGaiaPairing => {
                "GET_DEVICES_AVAILABLE_FOR_GAIA_PAIRING"
            }
            Self::CreateGaiaPairing => "CREATE_GAIA_PAIRING",
            Self::GetConversation => "GET_CONVERSATION",
            Self::CreateGaiaPairingClientInit => "CREATE_GAIA_PAIRING_CLIENT_INIT",
            Self::CreateGaiaPairingClientFinished => {
                "CREATE_GAIA_PAIRING_CLIENT_FINISHED"
            }
            Self::UnpairGaiaPairing => "UNPAIR_GAIA_PAIRING",
            Self::CancelGaiaPairing => "CANCEL_GAIA_PAIRING",
            Self::Prewarm => "PREWARM",
            Self::ConversationGroupNameSearch => "CONVERSATION_GROUP_NAME_SEARCH",
            Self::LinkRcsIdentity => "LINK_RCS_IDENTITY",
            Self::UnlinkRcsIdentity => "UNLINK_RCS_IDENTITY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNSPECIFIED" => Some(Self::Unspecified),
            "LIST_CONVERSATIONS" => Some(Self::ListConversations),
            "LIST_MESSAGES" => Some(Self::ListMessages),
            "SEND_MESSAGE" => Some(Self::SendMessage),
            "MESSAGE_UPDATES" => Some(Self::MessageUpdates),
            "LIST_CONTACTS" => Some(Self::ListContacts),
            "CONVERSATION_UPDATES" => Some(Self::ConversationUpdates),
            "GET_OR_CREATE_CONVERSATION" => Some(Self::GetOrCreateConversation),
            "MESSAGE_READ" => Some(Self::MessageRead),
            "BROWSER_PRESENCE_CHECK" => Some(Self::BrowserPresenceCheck),
            "TYPING_UPDATES" => Some(Self::TypingUpdates),
            "SETTINGS_UPDATE" => Some(Self::SettingsUpdate),
            "USER_ALERT" => Some(Self::UserAlert),
            "UPDATE_CONVERSATION" => Some(Self::UpdateConversation),
            "GET_UPDATES" => Some(Self::GetUpdates),
            "ACK_BROWSER_PRESENCE" => Some(Self::AckBrowserPresence),
            "LIST_STICKER_SETS" => Some(Self::ListStickerSets),
            "LEAVE_RCS_GROUP" => Some(Self::LeaveRcsGroup),
            "ADD_PARTICIPANT_TO_RCS_GROUP" => Some(Self::AddParticipantToRcsGroup),
            "GET_CONVERSATION_TYPE" => Some(Self::GetConversationType),
            "NOTIFY_DITTO_ACTIVITY" => Some(Self::NotifyDittoActivity),
            "DELETE_MESSAGE" => Some(Self::DeleteMessage),
            "INSTALL_STICKER_SET" => Some(Self::InstallStickerSet),
            "RESEND_MESSAGE" => Some(Self::ResendMessage),
            "GET_CONTACT_RCS_GROUP_STATUS" => Some(Self::GetContactRcsGroupStatus),
            "DOWNLOAD_MESSAGE" => Some(Self::DownloadMessage),
            "LIST_TOP_CONTACTS" => Some(Self::ListTopContacts),
            "GET_CONTACTS_THUMBNAIL" => Some(Self::GetContactsThumbnail),
            "CHANGE_PARTICIPANT_COLOR" => Some(Self::ChangeParticipantColor),
            "IS_BUGLE_DEFAULT" => Some(Self::IsBugleDefault),
            "STICKER_USER_CONTEXT" => Some(Self::StickerUserContext),
            "FAVORITE_STICKER_PACKS" => Some(Self::FavoriteStickerPacks),
            "RECENT_STICKERS" => Some(Self::RecentStickers),
            "UPDATE_RECENT_STICKERS" => Some(Self::UpdateRecentStickers),
            "GET_FULL_SIZE_IMAGE" => Some(Self::GetFullSizeImage),
            "GET_PARTICIPANTS_THUMBNAIL" => Some(Self::GetParticipantsThumbnail),
            "SEND_REACTION" => Some(Self::SendReaction),
            "SEND_REPLY" => Some(Self::SendReply),
            "GET_BLOB_FOR_ATTACHMENT" => Some(Self::GetBlobForAttachment),
            "GET_DEVICES_AVAILABLE_FOR_GAIA_PAIRING" => {
                Some(Self::GetDevicesAvailableForGaiaPairing)
            }
            "CREATE_GAIA_PAIRING" => Some(Self::CreateGaiaPairing),
            "GET_CONVERSATION" => Some(Self::GetConversation),
            "CREATE_GAIA_PAIRING_CLIENT_INIT" => Some(Self::CreateGaiaPairingClientInit),
            "CREATE_GAIA_PAIRING_CLIENT_FINISHED" => {
                Some(Self::CreateGaiaPairingClientFinished)
            }
            "UNPAIR_GAIA_PAIRING" => Some(Self::UnpairGaiaPairing),
            "CANCEL_GAIA_PAIRING" => Some(Self::CancelGaiaPairing),
            "PREWARM" => Some(Self::Prewarm),
            "CONVERSATION_GROUP_NAME_SEARCH" => Some(Self::ConversationGroupNameSearch),
            "LINK_RCS_IDENTITY" => Some(Self::LinkRcsIdentity),
            "UNLINK_RCS_IDENTITY" => Some(Self::UnlinkRcsIdentity),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageType {
    UnknownMessageType = 0,
    BugleMessage = 2,
    Gaia1 = 3,
    BugleAnnotation = 16,
    Gaia2 = 20,
}
impl MessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UnknownMessageType => "UNKNOWN_MESSAGE_TYPE",
            Self::BugleMessage => "BUGLE_MESSAGE",
            Self::Gaia1 => "GAIA_1",
            Self::BugleAnnotation => "BUGLE_ANNOTATION",
            Self::Gaia2 => "GAIA_2",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_MESSAGE_TYPE" => Some(Self::UnknownMessageType),
            "BUGLE_MESSAGE" => Some(Self::BugleMessage),
            "GAIA_1" => Some(Self::Gaia1),
            "BUGLE_ANNOTATION" => Some(Self::BugleAnnotation),
            "GAIA_2" => Some(Self::Gaia2),
            _ => None,
        }
    }
}
