// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "settings.Settings")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Settings {
    #[prost(message, repeated, tag = "2")]
    pub sim_cards: ::prost::alloc::vec::Vec<SimCard>,
    #[prost(message, optional, tag = "3")]
    pub op_code_data: ::core::option::Option<SomeData>,
    #[prost(message, optional, tag = "4")]
    pub rcs_settings: ::core::option::Option<RcsSettings>,
    #[prost(string, tag = "5")]
    pub bugle_version: ::prost::alloc::string::String,
    #[prost(bool, tag = "7")]
    pub bool1: bool,
    #[prost(message, optional, tag = "8")]
    pub bool_fields2: ::core::option::Option<BooleanFields2>,
    #[prost(bytes = "vec", tag = "9")]
    pub mysterious_bytes: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "10")]
    pub bool_fields3: ::core::option::Option<BooleanFields3>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "settings.SIMCard")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SimCard {
    #[prost(message, optional, tag = "3")]
    pub rcs_chats: ::core::option::Option<RcsChats>,
    #[prost(message, optional, tag = "5")]
    pub sim_data: ::core::option::Option<SimData>,
    #[prost(bool, tag = "6")]
    pub bool1: bool,
    #[prost(message, optional, tag = "7")]
    pub sim_participant: ::core::option::Option<SimParticipant>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "settings.RCSChats")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RcsChats {
    #[prost(bool, tag = "1")]
    pub enabled: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "settings.BoolMsg")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BoolMsg {
    #[prost(bool, tag = "1")]
    pub bool1: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "settings.SIMPayload")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SimPayload {
    /// 1 for payloads in non-self participants?
    #[prost(int32, tag = "1")]
    pub two: i32,
    #[prost(int32, tag = "2")]
    pub sim_number: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "settings.SIMData")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SimData {
    #[prost(message, optional, tag = "1")]
    pub sim_payload: ::core::option::Option<SimPayload>,
    /// maybe isDefault?
    #[prost(bool, tag = "2")]
    pub bool1: bool,
    #[prost(string, tag = "3")]
    pub carrier_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub color_hex: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub int1: i64,
    #[prost(string, tag = "6")]
    pub formatted_phone_number: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub international_phone_number: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "settings.UnknownMessage")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnknownMessage {
    #[prost(int64, tag = "1")]
    pub int1: i64,
    #[prost(int64, tag = "2")]
    pub int2: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "settings.SIMParticipant")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SimParticipant {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "settings.SomeData")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SomeData {
    #[prost(bool, tag = "3")]
    pub push_enabled: bool,
    #[prost(bool, tag = "7")]
    pub field7: bool,
    #[prost(bool, tag = "12")]
    pub field12: bool,
    #[prost(bytes = "vec", repeated, tag = "15")]
    pub some_emojis: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, tag = "16")]
    pub json_data: ::prost::alloc::string::String,
    #[prost(string, tag = "17")]
    pub some_string: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "settings.RCSSettings")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RcsSettings {
    #[prost(bool, tag = "1")]
    pub is_enabled: bool,
    #[prost(bool, tag = "2")]
    pub send_read_receipts: bool,
    #[prost(bool, tag = "3")]
    pub show_typing_indicators: bool,
    /// uncertain, but this field seems to disappear when gmessages is un-defaulted
    #[prost(bool, tag = "4")]
    pub is_default_sms_app: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "settings.BooleanFields2")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BooleanFields2 {
    #[prost(bool, tag = "1")]
    pub bool1: bool,
    #[prost(bool, tag = "2")]
    pub bool2: bool,
    #[prost(message, optional, tag = "3")]
    pub bool_msg1: ::core::option::Option<BoolMsg>,
    #[prost(message, optional, tag = "5")]
    pub bool_msg2: ::core::option::Option<BoolMsg>,
    #[prost(bool, tag = "6")]
    pub bool3: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "settings.BooleanFields3")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BooleanFields3 {
    #[prost(bool, tag = "1")]
    pub bool1: bool,
    #[prost(bool, tag = "3")]
    pub bool3: bool,
    #[prost(bool, tag = "4")]
    pub bool4: bool,
    #[prost(bool, tag = "5")]
    pub bool5: bool,
    #[prost(bool, tag = "6")]
    pub bool6: bool,
    #[prost(bool, tag = "7")]
    pub bool7: bool,
    #[prost(bool, tag = "8")]
    pub bool8: bool,
    #[prost(bool, tag = "9")]
    pub bool9: bool,
}
