// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "ukey.Ukey2Message")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ukey2Message {
    /// Identifies message type
    #[prost(enumeration = "ukey2_message::Type", tag = "1")]
    pub message_type: i32,
    /// Actual message, to be parsed according to message_type
    #[prost(bytes = "vec", tag = "2")]
    pub message_data: ::prost::alloc::vec::Vec<u8>,
}
/// Nested message and enum types in `Ukey2Message`.
pub mod ukey2_message {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Type {
        UnknownDoNotUse = 0,
        Alert = 1,
        ClientInit = 2,
        ServerInit = 3,
        ClientFinish = 4,
    }
    impl Type {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::UnknownDoNotUse => "UNKNOWN_DO_NOT_USE",
                Self::Alert => "ALERT",
                Self::ClientInit => "CLIENT_INIT",
                Self::ServerInit => "SERVER_INIT",
                Self::ClientFinish => "CLIENT_FINISH",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNKNOWN_DO_NOT_USE" => Some(Self::UnknownDoNotUse),
                "ALERT" => Some(Self::Alert),
                "CLIENT_INIT" => Some(Self::ClientInit),
                "SERVER_INIT" => Some(Self::ServerInit),
                "CLIENT_FINISH" => Some(Self::ClientFinish),
                _ => None,
            }
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "ukey.Ukey2Alert")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ukey2Alert {
    #[prost(enumeration = "ukey2_alert::AlertType", tag = "1")]
    pub r#type: i32,
    #[prost(string, tag = "2")]
    pub error_message: ::prost::alloc::string::String,
}
/// Nested message and enum types in `Ukey2Alert`.
pub mod ukey2_alert {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum AlertType {
        UnknownAlertType = 0,
        /// Framing errors
        ///
        /// The message could not be deserialized
        BadMessage = 1,
        /// message_type has an undefined value
        BadMessageType = 2,
        /// message_type received does not correspond to expected type at this stage of the protocol
        IncorrectMessage = 3,
        /// Could not deserialize message_data as per value in message_type
        BadMessageData = 4,
        /// ClientInit and ServerInit errors
        ///
        /// version is invalid; server cannot find suitable version to speak with client.
        BadVersion = 100,
        /// Random data is missing or of incorrect length
        BadRandom = 101,
        /// No suitable handshake ciphers were found
        BadHandshakeCipher = 102,
        /// The next protocol is missing, unknown, or unsupported
        BadNextProtocol = 103,
        /// The public key could not be parsed
        BadPublicKey = 104,
        /// Other errors
        ///
        /// An internal error has occurred.  error_message may contain additional details for logging and debugging.
        InternalError = 200,
    }
    impl AlertType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::UnknownAlertType => "UNKNOWN_ALERT_TYPE",
                Self::BadMessage => "BAD_MESSAGE",
                Self::BadMessageType => "BAD_MESSAGE_TYPE",
                Self::IncorrectMessage => "INCORRECT_MESSAGE",
                Self::BadMessageData => "BAD_MESSAGE_DATA",
                Self::BadVersion => "BAD_VERSION",
                Self::BadRandom => "BAD_RANDOM",
                Self::BadHandshakeCipher => "BAD_HANDSHAKE_CIPHER",
                Self::BadNextProtocol => "BAD_NEXT_PROTOCOL",
                Self::BadPublicKey => "BAD_PUBLIC_KEY",
                Self::InternalError => "INTERNAL_ERROR",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNKNOWN_ALERT_TYPE" => Some(Self::UnknownAlertType),
                "BAD_MESSAGE" => Some(Self::BadMessage),
                "BAD_MESSAGE_TYPE" => Some(Self::BadMessageType),
                "INCORRECT_MESSAGE" => Some(Self::IncorrectMessage),
                "BAD_MESSAGE_DATA" => Some(Self::BadMessageData),
                "BAD_VERSION" => Some(Self::BadVersion),
                "BAD_RANDOM" => Some(Self::BadRandom),
                "BAD_HANDSHAKE_CIPHER" => Some(Self::BadHandshakeCipher),
                "BAD_NEXT_PROTOCOL" => Some(Self::BadNextProtocol),
                "BAD_PUBLIC_KEY" => Some(Self::BadPublicKey),
                "INTERNAL_ERROR" => Some(Self::InternalError),
                _ => None,
            }
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "ukey.Ukey2ClientInit")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Ukey2ClientInit {
    /// highest supported version for rollback protection
    #[prost(int32, tag = "1")]
    pub version: i32,
    /// random bytes for replay/reuse protection
    #[prost(bytes = "vec", tag = "2")]
    pub random: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "3")]
    pub cipher_commitments: ::prost::alloc::vec::Vec<
        ukey2_client_init::CipherCommitment,
    >,
    /// Next protocol that the client wants to speak.
    #[prost(string, tag = "4")]
    pub next_protocol: ::prost::alloc::string::String,
}
/// Nested message and enum types in `Ukey2ClientInit`.
pub mod ukey2_client_init {
    /// One commitment (hash of ClientFinished containing public key) per supported cipher
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(::prost_reflect::ReflectMessage)]
    #[prost_reflect(message_name = "ukey.Ukey2ClientInit.CipherCommitment")]
    #[prost_reflect(
        file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES"
    )]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct CipherCommitment {
        #[prost(enumeration = "super::Ukey2HandshakeCipher", tag = "1")]
        pub handshake_cipher: i32,
        #[prost(bytes = "vec", tag = "2")]
        pub commitment: ::prost::alloc::vec::Vec<u8>,
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "ukey.Ukey2ServerInit")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ukey2ServerInit {
    /// highest supported version for rollback protection
    #[prost(int32, tag = "1")]
    pub version: i32,
    /// random bytes for replay/reuse protection
    #[prost(bytes = "vec", tag = "2")]
    pub random: ::prost::alloc::vec::Vec<u8>,
    /// Selected Cipher and corresponding public key
    #[prost(enumeration = "Ukey2HandshakeCipher", tag = "3")]
    pub handshake_cipher: i32,
    #[prost(message, optional, tag = "4")]
    pub public_key: ::core::option::Option<GenericPublicKey>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "ukey.Ukey2ClientFinished")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ukey2ClientFinished {
    /// public key matching selected handshake cipher
    #[prost(message, optional, tag = "1")]
    pub public_key: ::core::option::Option<GenericPublicKey>,
}
/// A convenience proto for encoding NIST P-256 elliptic curve public keys
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "ukey.EcP256PublicKey")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EcP256PublicKey {
    /// x and y are encoded in big-endian two's complement (slightly wasteful)
    /// Client MUST verify (x,y) is a valid point on NIST P256
    #[prost(bytes = "vec", tag = "1")]
    pub x: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub y: ::prost::alloc::vec::Vec<u8>,
}
/// A convenience proto for encoding RSA public keys with small exponents
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "ukey.SimpleRsaPublicKey")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SimpleRsaPublicKey {
    /// Encoded in big-endian two's complement
    #[prost(bytes = "vec", tag = "1")]
    pub n: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag = "2")]
    pub e: i32,
}
/// A convenience proto for encoding Diffie-Hellman public keys,
/// for use only when Elliptic Curve based key exchanges are not possible.
/// (Note that the group parameters must be specified separately)
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "ukey.DhPublicKey")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DhPublicKey {
    /// Big-endian two's complement encoded group element
    #[prost(bytes = "vec", tag = "1")]
    pub y: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "ukey.GenericPublicKey")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GenericPublicKey {
    #[prost(enumeration = "PublicKeyType", tag = "1")]
    pub r#type: i32,
    #[prost(oneof = "generic_public_key::PublicKey", tags = "2, 3, 4")]
    pub public_key: ::core::option::Option<generic_public_key::PublicKey>,
}
/// Nested message and enum types in `GenericPublicKey`.
pub mod generic_public_key {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum PublicKey {
        #[prost(message, tag = "2")]
        EcP256PublicKey(super::EcP256PublicKey),
        #[prost(message, tag = "3")]
        Rsa2048PublicKey(super::SimpleRsaPublicKey),
        /// Use only as a last resort
        #[prost(message, tag = "4")]
        Dh2048PublicKey(super::DhPublicKey),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Ukey2HandshakeCipher {
    Reserved = 0,
    /// NIST P-256 used for ECDH, SHA512 used for commitment
    P256Sha512 = 100,
    /// Curve 25519 used for ECDH, SHA512 used for commitment
    Curve25519Sha512 = 200,
}
impl Ukey2HandshakeCipher {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Reserved => "RESERVED",
            Self::P256Sha512 => "P256_SHA512",
            Self::Curve25519Sha512 => "CURVE25519_SHA512",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RESERVED" => Some(Self::Reserved),
            "P256_SHA512" => Some(Self::P256Sha512),
            "CURVE25519_SHA512" => Some(Self::Curve25519Sha512),
            _ => None,
        }
    }
}
/// A list of supported public key types
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PublicKeyType {
    UnknownPublicKeyType = 0,
    EcP256 = 1,
    Rsa2048 = 2,
    /// 2048-bit MODP group 14, from RFC 3526
    Dh2048Modp = 3,
}
impl PublicKeyType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UnknownPublicKeyType => "UNKNOWN_PUBLIC_KEY_TYPE",
            Self::EcP256 => "EC_P256",
            Self::Rsa2048 => "RSA2048",
            Self::Dh2048Modp => "DH2048_MODP",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_PUBLIC_KEY_TYPE" => Some(Self::UnknownPublicKeyType),
            "EC_P256" => Some(Self::EcP256),
            "RSA2048" => Some(Self::Rsa2048),
            "DH2048_MODP" => Some(Self::Dh2048Modp),
            _ => None,
        }
    }
}
