// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "util.EmptyArr")]
#[prost_reflect(file_descriptor_set_bytes = "crate::PBLITE_FILE_DESCRIPTOR_SET_BYTES")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EmptyArr {}
